### ISSUE TITLE
Beacon node restart takes 5 minutes

### ISSUE THREAD

**Issue by dvush** [sigp/lighthouse#5289] opened 2024-02-24 11:08 UTC
## Description

After routine service restart lighthouse beacon node takes around 5 minutes to be up and running again and during that time validator is offline and missing attestations.

## Version

```
Lighthouse v5.0.0-b5bae6e
BLS library: blst
SHA256 hardware acceleration: false
Allocator: jemalloc
Profile: maxperf
Specs: mainnet (true), minimal (false), gnosis (true)
```

Linux version:
```
Linux ethereumonarm-orangepi5-plus-220e4d7fd 5.10.160-legacy-rk35xx #1 SMP Tue Nov 28 02:45:16 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

## Present Behaviour

After the lighthouse service restart it takes about 5 minutes for it to be live.

logs:

```
Feb 24 10:45:20.448 INFO Logging to file                         path: "/home/ethereum/.lighthouse/mainnet/beacon/logs/beacon.log"
Feb 24 10:45:20.462 INFO Lighthouse started                      version: Lighthouse/v5.0.0-b5bae6e
Feb 24 10:45:20.462 INFO Configured for network                  name: mainnet
Feb 24 10:45:20.462 INFO Data directory initialised              datadir: /home/ethereum/.lighthouse/mainnet
Feb 24 10:45:20.467 INFO Deposit contract                        address: 0x00000000219ab540356cbb839cbe05303d7705fa, deploy_block: 11184524
Feb 24 10:45:20.697 INFO Hot-Cold DB initialized                 split_state: 0x69aa0f1318d41d228ebdb5c498a90ce81b96177778e04cd57f60c22f09d056cd, split_slot: 8495552, service: freezer_db
Feb 24 10:45:20.698 INFO Blob DB initialized                     oldest_blob_slot: Some(Slot(8626176)), path: "/home/ethereum/.lighthouse/mainnet/beacon/blobs_db", service: freezer_db
Feb 24 10:45:20.725 INFO Using external block builder            local_user_agent: Lighthouse/v5.0.0-b5bae6e, builder_url: "http://localhost:18550/", service: exec
Feb 24 10:45:20.726 INFO Refusing to checkpoint sync             msg: database already exists, use --purge-db to force checkpoint sync, service: beacon
Feb 24 10:45:20.726 INFO Starting beacon chain                   method: resume, service: beacon
Feb 24 10:51:56.930 INFO Block production enabled                method: json rpc via http, endpoint: Auth { endpoint: "http://127.0.0.1:8551/", jwt_path: "/etc/ethereum/jwtsecret", jwt_id: None, jwt_version: None>
Feb 24 10:52:00.455 INFO Beacon chain initialized                head_slot: 8495618, head_block: 0x3d8c…7057, head_state: 0x8de7…49e9, service: beacon
Feb 24 10:52:00.455 INFO Timer service started                   service: node_timer
```

Notice the gap after "Starting beacon chain".
During that time lighthouse validator was complaining about beacon node connection and that lead to missing attestation.

```
Feb 24 10:45:06.275 WARN Offline beacon node                     endpoint: http://localhost:5052/, error: HttpClient(url: http://localhost:5052/, kind: request, detail: error trying to connect: tcp connect error: >
Feb 24 10:45:06.275 WARN Unable to connect to a beacon node      available: 0, total: 1, retry in: 2 seconds
Feb 24 10:45:08.277 WARN Offline beacon node                     endpoint: http://localhost:5052/, error: HttpClient(url: http://localhost:5052/, kind: request, detail: error trying to connect: tcp connect error: >
Feb 24 10:45:08.277 WARN Unable to connect to a beacon node      available: 0, total: 1, retry in: 2 seconds
```

## Expected Behaviour

The restart should be much faster. For example, on the same machine EL node (nethermind) restarted in less than 10 seconds.

**Comment by michaelsproul** [comment] 2024-02-24 11:39
The reason for this is described here:

- https://github.com/sigp/lighthouse/issues/3505

We've fixed that issue in the tree-states database upgrade which is under alpha testing at the moment and stabilising shortly after Deneb on mainnet

**Comment by michaelsproul** [comment] 2024-02-25 23:24
Closing as duplicate of #3505

**Closed as not planned by michaelsproul** 2024-02-25 23:24 UTC
