### ISSUE TITLE
Implement 2 minutes beacon node sync with checkpoint state

### ISSUE THREAD

**Issue by remyroy** [sigp/lighthouse#2328] opened 2021-04-30 12:32 UTC
## Description

Implement a *fast* way to sync the beacon node from scratch using a checkpoint state. See [this video by Adrian Sutton](https://www.youtube.com/watch?v=ce9uVRl23zI) from the Teku development team. You can get more details on [the related Teku documentation page](https://docs.teku.pegasys.tech/en/latest/HowTo/Get-Started/Checkpoint-Start/).

## Present Behaviour

It can take a few hours to sync a Lighthouse beacon node on mainnet or any of the testnet from scratch.

## Expected Behaviour

It should take only 2 minutes to sync a Lighthouse beacon node from scratch using a recent finalized checkpoint state.

## Steps to resolve

Implement syncing using a provided checkpoint state.

**Comment by michaelsproul** [comment] 2021-04-30 13:30
This is a much desired feature for us too! We have it 90% implemented on this branch and will finish it off as soon as we have some bandwidth: https://github.com/sigp/lighthouse/pull/2244

The main piece remaining is backfilling state (syncing backwards)

**Comment by remyroy** [comment] 2021-04-30 13:32
Sorry. Looks like this is a duplicate.

**Comment by michaelsproul** [comment] 2021-04-30 14:06
Yeah, I'll close as duplicate of https://github.com/sigp/lighthouse/issues/1891

**Closed as completed by michaelsproul** 2021-04-30 14:06 UTC
