### ISSUE TITLE
Graffiti ""

### ISSUE THREAD

**Issue by MysticRyuujin** [sigp/lighthouse#2054] opened 2020-12-06 03:24 UTC
## Description

`--graffiti=""` results in graffiti of `""` which seems strange when setting it as a flag in docker compose file.

## Version

Docker 1.0.3

## Present Behaviour

`--graffiti=""` results in graffiti of `""`

## Expected Behaviour

`--graffiti=""` results in no graffiti

## Steps to resolve

I'm actually not sure how to just set a blank graffiti without using a flag that does other things too?

**Comment by michaelsproul** [comment] 2020-12-06 08:13
Hmm, I can't reproduce this locally so I'm wondering if there's something peculiar about your setup that's causing this.

1. What shell are you using? Both shells I tried (`fish` and `bash`) strip the quotes from the string before passing it to Lighthouse. i.e. they treat `--graffiti=""` exactly the same as `--graffiti=` (the latter here could be a workaround for you).
2. Are you sure you're not using smart quotes, like `“”`? These often get auto-inserted in various editors/browsers, but are not compatible with the shell.

**Comment by MysticRyuujin** [comment] 2020-12-06 14:59
Are you running it via Docker-Compose file? I typed the quotes myself so I know they're real quotes :)

```
version: "3.3"
services:
  lh-beacon:
    container_name: lh-beacon
    image: "sigp/lighthouse:v1.0.3"
    ports:
      - "5052:5052" # RESTful HTTP API server
      - "5053:5053" # WebSocket
      - "9000:9000" # Peering
      - "9000:9000/udp" # Peering
    volumes:
      - "/data/dockerfiles/lh-beacon:/root/.lighthouse"
    stop_signal: SIGINT
    stop_grace_period: 2m
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    command:
      - lighthouse
      - --network=mainnet
      - beacon_node
      - --slasher
      - --disable-upnp
      - --eth1
      - --http
      - --http-address=0.0.0.0
      - --metrics
      - --metrics-address=0.0.0.0
      - --ws
      - --ws-address=0.0.0.0
      - --target-peers=100
      - --eth1-endpoints=<redacted>
      - --graffiti=""
```

**Comment by michaelsproul** [comment] 2020-12-07 04:46
> Or some weird docker interpretation?

Ah, looking at your compose file I'm pretty sure it's this. The way the YAML is getting parsed means the string given to the Lighthouse binary for that argument is `"--graffiti=\"\""`. I think either of these should work fine:

1. `--graffiti=`
2.

```
- --graffiti
- ""
```

There's some more about YAML quoting here that might be interesting :sweat_smile:  https://www.yaml.info/learn/quote.html

I'm going to close this issue because Lighthouse itself is behaving correctly in this case and it's just a matter of weird input from Docker. We can re-open if neither of the snippets above works for you

**Closed** 2020-12-07 04:46 UTC
