### ISSUE TITLE
No valid eth1_data votes, `votes_to_consider` empty, outcome: casting `state.eth1_data` as eth1 vote

### ISSUE THREAD

**Issue by q9f** [sigp/lighthouse#1066] opened 2020-04-27 12:29 UTC
## Description

I'm unsure this is an actual issue, but reporting it here because my beacon node on Schlesi keeps reporting it as `ERRO`.

```
No valid eth1_data votes, `votes_to_consider` empty, outcome: casting `state.eth1_data` as eth1 vote, genesis_time: 1587981600, earliest_block_timestamp: 1587974284, lowest_block_number: 2596126, service: beacon
```

## Version

Using Lighthouse from this branch #1052 @ 310cc4fb504f6b3d6f4b0e9a5f53715a0c848138

Using Schlesi config: https://github.com/goerli/schlesi

## Present Behavior

Connected a validator client to a beacon node locally.

```
Apr 27 11:12:37.439 INFO Beacon chain initialized                head_slot: 0, head_block: 0xc9cb…db82, head_state: 0x55f8…c2fc, service: beacon
Apr 27 11:12:37.439 INFO Libp2p Service                          peer_id: PeerId("16Uiu2HAmP2QxXy9hgzC52faSZrhqJVXK3uakEWA7xxDXXNMfz9ZL"), service: network
Apr 27 11:12:37.440 INFO ENR Initialised                         tcp: Some(9000), udp: Some(9000), ip: Some(127.0.0.1), id: 0xfdf9..be7c, seq: 1, enr: enr:-LK4QBewQubLzZvDu7ZHKFZspEy-zG8ODc67ip1vfuV4UagqL7PaxgGUGvjZy9mgE4X0ALGQ8KwT60_Mp-OJHX4vF5sBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCZJe_WAAAAAP__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQOaEePmecbj4Y1ONUa4TtS21fRyIUlKwEVfa5BZJPtMe4N0Y3CCIyiDdWRwgiMo, service: network
Apr 27 11:12:37.440 INFO Listening established                   address: /ip4/0.0.0.0/tcp/9000/p2p/16Uiu2HAmP2QxXy9hgzC52faSZrhqJVXK3uakEWA7xxDXXNMfz9ZL, service: network
Apr 27 11:12:37.440 INFO Subscribed to topics                    topics: [BeaconBlock, BeaconAggregateAndProof, VoluntaryExit, ProposerSlashing, AttesterSlashing], service: network
Apr 27 11:12:37.440 INFO HTTP API started                        port: 5052, address: 127.0.0.1, service: http
Apr 27 11:12:37.447 WARN Received old metadata                   new_seq_no: 0, known_seq_no: 0, peer_id: 16Uiu2HAmEHdW4czXphgYtFsbK1zyUrvHW23AEYxym6e5uftA6bV5, service: network
Apr 27 11:12:37.469 INFO Address updated                         udp_port: 9000, ip: 192.168.0.121, service: network
Apr 27 11:12:37.470 WARN Received old metadata                   new_seq_no: 0, known_seq_no: 0, peer_id: 16Uiu2HAm3PGdRXquDUWF52L13n9WwY2zMcrLrctEbV3AUMKQJLQQ, service: network
Apr 27 11:12:38.620 INFO Address updated                         udp_port: 9000, ip: 87.180.198.9, service: network
Apr 27 11:54:28.882 INFO Sync state updated                      new_state: Synced, old_state: Stalled, service: sync, service: network
Apr 27 12:00:06.001 INFO Synced                                  slot: 0, epoch: 0, finalized_epoch: 0, finalized_root: 0x0000…0000, peers: 3, service: slot_notifier
Apr 27 12:00:18.001 INFO Synced                                  slot: 1, epoch: 0, finalized_epoch: 0, finalized_root: 0x0000…0000, peers: 3, service: slot_notifier
Apr 27 12:00:24.158 ERRO No valid eth1_data votes, `votes_to_consider` empty, outcome: casting `state.eth1_data` as eth1 vote, genesis_time: 1587981600, earliest_block_timestamp: 1587974284, lowest_block_number: 2596126, service: beacon
Apr 27 12:00:24.181 INFO Block from local validator              block_slot: 2, block_root: 0x4a7f…774a, service: http
Apr 27 12:00:30.001 INFO Synced                                  slot: 2, epoch: 0, finalized_epoch: 0, finalized_root: 0x0000…0000, peers: 3, service: slot_notifier
Apr 27 12:00:36.185 ERRO No valid eth1_data votes, `votes_to_consider` empty, outcome: casting `state.eth1_data` as eth1 vote, genesis_time: 1587981600, earliest_block_timestamp: 1587974284, lowest_block_number: 2596126, service: beacon
Apr 27 12:00:36.206 INFO Block from local validator              block_slot: 3, block_root: 0xfc21…3d6e, service: http
Apr 27 12:00:42.001 INFO Synced                                  slot: 3, epoch: 0, finalized_epoch: 0, finalized_root: 0x0000…0000, peers: 3, service: slot_notifier
```

## Expected Behavior

Should not ERROR :)

I can't actually tell what the implications are.

## Steps to resolve

N/A

---

This only happens on the beacon node where the validator client is connected to.

**Comment by paulhauner** [comment] 2020-04-27 22:37
I think this is an issue we've seen a few times which stems from a configuration problem. If the warning eventually goes away then it would be consistent with what I've observed.

The issue is when the time between eth1 genesis and eth2 genesis is shorter than `ETH1_FOLLOW_DISTANCE`. What will happen is the node will reach back prior to genesis (or even contract deployment) when it tries to vote making it impossible to cast a valid vote.

This issue can even result in a chain-stopping bug where the node becomes unable to produce a valid block because the eth1 vote would cause the deposit count to go backwards (I swear I raised an issue on the spec for this, but I can't find it; will follow up).

For testnets with short `MIN_GENESIS_TIME` I would recommend setting `ETH1_FOLLOW_DISTANCE` to something appropriately short.

I think we can close this as a "configuration issue" if you can confirm:
- `MIN_GENESIS_TIME < ETH1_FOLLOW_DISTANCE * SECONDS_PER_ETH1_BLOCK`
- The node eventually stopped showing this error.

Perhaps it would be nice if we added a warning when this is the case. If you think this would be sensible, feel free to make a feature-request issue :)

**Comment by q9f** [comment] 2020-04-28 08:40
> `MIN_GENESIS_TIME < ETH1_FOLLOW_DISTANCE * SECONDS_PER_ETH1_BLOCK`

`MIN_GENESIS_TIME` or `MIN_GENESIS_DELAY`?

> The node eventually stopped showing this error.

I can confirm this.

**Closed** 2020-04-30 10:07 UTC
