### ISSUE TITLE
Silent Failure after Cache Lock Timeout

### ISSUE THREAD

**Issue by Brianfit** [sigp/lighthouse#2271] opened 2021-03-18 12:49 UTC
## Description

After a brief loss of connectivity and Cache Lock Timeout, Lighthouse continues to log Block Received and Synced messages despite attestations actually failing

## Version

Lighthouse v1.1.3-46920a8

## Present Behaviour

VC fails, Attestations fail, log carries on with INFO messages  

## Expected Behaviour

VC fails, Attestations fail, log issues CRIT or ERRO warning that VC is down

## Steps to resolve

Rebooted system. Source of problem causing OOM reaper to shut down lighthouse vc unknown.  

## Syslog:

[WTFMar13Log.txt](https://www.brian-fitzgerald.net/wtflog/WTFMar13Log.txt)

**Comment by pawanjay176** [comment] 2021-03-18 13:06
Could you reupload the logs? I think it didn't upload properly.

**Comment by Brianfit** [comment] 2021-03-18 16:09
@pawanjay176 Sorry about that. Fixed.

**Comment by michaelsproul** [comment] 2021-03-18 22:57
Interpreting the logs:

1. It looks like the Lighthouse beacon node (PID 251005) was killed by the OOM killer, and its resident set size was ~3.79GB when it was killed. This is about what we expect these days for mainnet, without the use of the [memory allocator hack described here](https://lighthouse.sigmaprime.io/update-34.html) (which we are not yet ready to enable universally).
2. Your `systemd` setup gracefully stopped the Lighthouse validator client (PID 250997) on the line `Stopping Lighthouse Eth2 Client Validator Node`, seemingly because you have it set up to stop whenever the BN stops? I think this is the root of the problem: systemd stopped the VC and never restarted it. There's no `Started Lighthouse Eth2 Client Validator Node` as there is for the beacon node (`Started Lighthouse Beacon Node`).
3. The BN (post restart) proceeded to experience the validator pubkey lock timeout (which is caused by the CPU being overloaded usually), and then gracefully recovered and regained sync. As far as I can tell from those logs the BN was doing the best it could in the conditions, and nothing I've seen is indicative of a bug in Lighthouse.

My recommendations are:

* Tweak your systemd service files so that the validator client doesn't shutdown and stay down if the BN dies. It's safe to keep it running even if the BN goes down.
* Try to reduce the memory pressure, either by using the memory hack I linked, removing Geth from the node, or (sorry to say it) moving to more powerful hardware. It's also possible that system load will settle down once Geth finishes constructing its snapshot.

Let us know if you need help, hopefully we can get your validator up and running smoothly.

**Comment by michaelsproul** [comment] 2021-03-18 23:15
I'm trying to work out what systemd configuration would case the behaviour you're experiencing. Would you mind posting the contents of any Lighthouse-related `.service` files from `/etc/systemd/system/`?

**Comment by Brianfit** [comment] 2021-03-19 17:47
Thanks, Michael. I appreciate the detailed forensics -- very helpful. And to be clear, I was back up and running on reboot. I've been preparing a move of Geth on to another Pi to reduce memory pressure, and will finish that job this weekend. I've had a couple other instances of out-of-memory events, but I thought I'd solved it by removing glances as a background process.  
 
> Your systemd setup gracefully stopped the Lighthouse validator client (PID 250997) on the line Stopping Lighthouse Eth2 
> Client Validator Node, seemingly because you have it set up to stop whenever the BN stops?

Not knowingly! I followed the Somer Esat guides without any modification to the .service files other than cranking down the geth cache size.

Here are links to my [lighthousebeacon.service](https://brian-fitzgerald.net/wtflog/lighthousebeacon.service.txt) and [lighthousevalidator.service ](https://brian-fitzgerald.net/wtflog/lighthousevalidator.service.txt)

Perhaps this is a Feature Request instead of a bug report: that the Beacon Node detect when the validator is not running, and indicate its state via a CRIT report.

The sad fact is that I had unknowingly switched off notifications from beaconcha.in. I do a daily look at the log for any problems and saw the CRIT warning about the Cache failure, but what appeared to be full recovery and normal info messages indicating all was well -- but in fact my attestations were failing.  Had I been more rigorous in parsing the log, and maintained the discipline of checking Beaconcha.in I would have known action was required. Missed a block proposal as a result. So thought it might benefit someone in the future to see a log shout that action was required.  

Thanks again and appreciate both what you and the Lighthouse team do and your excellent communications.

**Comment by paulhauner** [comment] 2021-04-23 10:29
> that the Beacon Node detect when the validator is not running, and indicate its state via a CRIT report.

I agree that this would be nice, however the BN/VC relationship is structured such that the BN has no knowledge of the validator client. It's annoying in this case, but it's very nice in many other cases (such as your VC being able to arbitrarily switch to any other BN on the fly).

I think what would really help you here is the `--validator-monitor-auto` flag on `lighthouse bn`. If you add this flag to your BN, it will infer which validators are your own (based on requests from the VC) and then give you `ERRO` logs if it detects they aren't performing well. It'll also give you `INFO` logs when they *are* performing well and some Prometheus metrics. You can read more about it here: https://lighthouse-book.sigmaprime.io/validator-monitoring.html

> Thanks again and appreciate both what you and the Lighthouse team do and your excellent communications.

Thanks for the positive feedback, it means a lot!

I'm going to close this one since I think we've addressed the issue here. Please feel free to reopen if you disagree :)

**Closed as completed by paulhauner** 2021-04-23 10:30 UTC
