### ISSUE TITLE
Validator node does not start after updating from v1.1.0 to v1.1.1

### ISSUE THREAD

**Issue by maurodelazeri** [sigp/lighthouse#2208] opened 2021-02-17 17:57 UTC
## Description

Please provide a brief description of the issue.

I use the client with docker... I cant update from the previous version to the new version

Previous version:

```
Lighthouse v1.1.0-e4b6213
BLS Library: blst-portable
Specs: mainnet (true), minimal (false), v0.12.3 (false)
```

New version: latest

## Version

Please provide your Lighthouse and Rust version. Are you building from
`stable` or `unstable`, which commit?

```
Lighthouse v1.1.0-e4b6213
BLS Library: blst-portable
Specs: mainnet (true), minimal (false), v0.12.3 (false)
```

## Present Behaviour

The beacon node works fine, but the validator does not start, it shows the follows:

```
root@venus:~/eth2-stack/stack/testnet# docker logs validator_node --follow --tail 10
versionnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
: Lighthouse/v1.1.1-f819ba5
Feb 17 17:29:07.054 INFO Configured for network                  name: pyrmont
Feb 17 17:29:07.054 INFO Starting validator client               validator_dir: "/var/lib/lighthouse/validators", beacon_nodes: ["http://beacon_node:5052"]
Feb 17 17:35:03.227 INFO Shutting down..
Feb 17 17:35:07.823 INFOthread 'tokio-runtime-worker' panicked at 'missing scheme', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.0/src/filters/cors.rs:620:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 Lighthouse started                      version: Lighthouse/v1.1.1-f819ba5
Feb 17 17:35:07.823 INFO Configured for network                  name: pyrmont
Feb 17 17:35:07.824 INFO Starting validator client               validator_dir: "/var/lib/lighthouse/validators", beacon_nodes: ["http://beacon_node:5052"]
^C
```

and with `RUST_BACKTRACE=1`

```
root@venus:~/eth2-stack/stack/testnet# docker logs validator_node --follow --tail 10
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: std::thread::local::LocalKey<T>::with
  14: tokio::runtime::thread_pool::worker::Context::run_task
  15: tokio::runtime::thread_pool::worker::Context::run
  16: tokio::macros::scoped_tls::ScopedKey<T>::set
  17: tokio::runtime::thread_pool::worker::run
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  19: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  20: tokio::runtime::task::harness::Harness<T,S>::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Describe the present behaviour of the application, with regards to this
issue.

## Expected Behaviour

should work, if I rollback to the previous version it works fine

## Steps to resolve

You can use the docker-composer bellow:

```
version: "3"

networks:
  monitor-net:
    driver: bridge

services:
  validator_node:
    image: sigp/lighthouse
    networks:
      - monitor-net
    container_name: validator_node
    hostname: validator_node
    restart: unless-stopped
    ports:
      - 5064:5064/tcp     # metrics endpoint
    volumes:
      - ./lighthouse:/var/lib/lighthouse
    depends_on:
        - beacon_node
        - geth
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - lighthouse
      - vc
      - --network 
      - pyrmont
      - --metrics
      - --metrics-address
      - "0.0.0.0"
      - --metrics-allow-origin
      - "*"
      - --metrics-port
      - "5064"
      - --beacon-nodes
      - http://beacon_node:5052
      - --graffiti 
      - "House Stark Dev"
      - --datadir 
      - /var/lib/lighthouse
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
        
  beacon_node:
    image: sigp/lighthouse
    networks:
      - monitor-net
    container_name: beacon_node
    hostname: beacon_node
    restart: unless-stopped
    ports:
      - 5052:5052/tcp
      - 5053:5053/tcp
      - 5054:5054/tcp     # metrics endpoint
      - 9000:9000/tcp
      - 9000:9000/udp
    volumes:
      - ./lighthouse:/var/lib/lighthouse
    depends_on:
        - geth
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - lighthouse
      - bn
      - --validator-monitor-auto
      - --slasher
      - --debug-level 
      - debug
      - --slasher-dir
      - /var/lib/lighthouse
      - --slasher-history-length 
      - "256" 
      - --slasher-max-db-size 
      - "16"
      - --network
      - pyrmont
      - --datadir
      - /var/lib/lighthouse
      - --staking
      - --metrics
      - --metrics-address
      - "0.0.0.0"
      - --metrics-allow-origin
      - "*"
      - --metrics-port
      - "5054"
      - --http
      - --http-allow-origin
      - "*"
      - --http-address
      - "0.0.0.0"
      - --subscribe-all-subnets
      - --import-all-attestations
      - --eth1-endpoints
      - http://geth:8545
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
  geth:
    image: ethereum/client-go:v1.9.25
    networks:
      - monitor-net
    container_name: geth
    hostname: geth
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
      - "6060:6060"
    volumes:
      - ./goethereum:/var/lib/goethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --goerli
      - --nousb
      - --http
      - --syncmode=fast
      - --nousb
      - --cache=4096
      - --maxpeers=50
      - --metrics
      - --pprof
      - --pprof.addr=0.0.0.0
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api
      - "eth,net,web3"
      - --datadir
      - "/var/lib/goethereum"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  nodeexporter:
    image: prom/node-exporter:v1.0.1
    hostname: nodeexporter
    ports:
      - 9100:9100/tcp
    networks:
      - monitor-net
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.7
    hostname: nodeexporter
    ports:
      - 8080:8080/tcp
    networks:
      - monitor-net
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```

**Comment by maurodelazeri** [comment] 2021-02-17 17:59
the example above is the `testnet`, I normally leave it running for a while before put it in the mainnet

**Comment by realbigsean** [comment] 2021-02-17 18:58
Hi @maurodelazeri , this is because the wildcard symbol`'*'` isn't available for the `--http-allow-origin` and `--metrics-allow-origin` flags at the moment. It isn't supported in one of our upstream dependencies, and we had added it into a forked version as a workaround, but during latest lighthouse update we've moved back to the original dependency. So you could either remove the flags entirely (I'm not sure about your set up but it's very possible this will have no impact to you) or you could be explicit about which "origins" you'd like to enable CORS for. We are working on either adding the feature to the upstream or updating our forked version

Relevant issue: #2205

**Comment by realbigsean** [comment] 2021-02-17 18:58
Closing this because it's a duplicate of #2205

**Closed as completed by realbigsean** 2021-02-17 18:58 UTC

**Comment by maurodelazeri** [comment] 2021-02-17 21:36
hey @realbigsean got it... I will keep running the 1.1.0 and follow the #2205
Thanks
