### ISSUE TITLE
Docker image doesn't contain lcli command

### ISSUE THREAD

**Issue by xaviarias** [sigp/lighthouse#2161] opened 2021-01-18 12:27 UTC
## Description

I'm trying to run the Docker latest unstable using the Local Testnet scripts, but doesn't contain Lighthouse binaries: 

`lcli: command not found`

## Version

Building from Docker [latest unstable image](https://hub.docker.com/layers/sigp/lighthouse/latest-unstable/images/sha256-a4c2e9ff5e06fdf6e7ebed86bf7545e27cf24edbba9ab10d9c9ea49f90d5e1f5).

## Present Behaviour

When starting the Docker image and running the Local testnet scripts inside the container, this message is shown:

```
12:53:43.705 [main] INFO  🐳 [sigp/lighthouse:latest] - Creating container for image: sigp/lighthouse:latest
12:53:46.269 [main] INFO  🐳 [sigp/lighthouse:latest] - Starting container with ID: c4b7badac4e3133b4b393e41fd9140352cf806ab40c67fd6e1713dc1f25386ed
12:53:46.663 [main] INFO  🐳 [sigp/lighthouse:latest] - Container sigp/lighthouse:latest is starting: c4b7badac4e3133b4b393e41fd9140352cf806ab40c67fd6e1713dc1f25386ed
Specification generated at /root/.lighthouse/local-testnet/testnet.
Generating 1024 validators concurrently... (this may take a while)
./setup.sh: line 11: lcli: command not found
```

## Expected Behaviour

In the previous versions, the command `lcli` was available inside the Docker container.

## Steps to resolve

Run the Docker image mapping the Local testnet scripts to the root directory. Then run `start.sh` inside the container.

**Comment by michaelsproul** [comment] 2021-01-18 13:18
Closing as a duplicate of https://github.com/sigp/lighthouse/issues/2087

We hope to improve this soon

**Closed by michaelsproul** 2021-01-18 13:18 UTC
