### ISSUE TITLE
Dependency cleanup prior to mainnet

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1926] opened 2020-11-17 23:37 UTC
## Description

We currently have in place a number of forks in non-canonical repositories which are required as the underlying dependencies have not updated to the latest ecosystem versions. 

Along side this we have dependencies of varying versions and we should, where possible attempt to combine them all into a single version. 

Before going to mainnet we should also update all dependencies to their latest version. 

Specific forked deps that should be looked at are:
- sigp/warp
- sigp/unsigned_varint
- sigp/rust-libp2p

**Comment by bachp** [comment] 2020-11-25 22:52
While attempting to package lighthouse for [NixOS](https://nixos.org/) I also run into issues with.

- sigp/discv5 - which is included from git and not from crates.io
- sigp/blst - which can't be properly cargo vendored when used from git

Cleaning these up would help.

**Comment by AgeManning** [comment] 2020-11-26 07:33
Yeah the discv5 dep is sorted in #1839 which will be merging to stable within the next day. 

I think the blst library has a new version we can target. @kirk-baird

**Comment by sean-sn** [comment] 2020-11-26 18:13
Submitted [#1979 ](https://github.com/sigp/lighthouse/pull/1979) which could be used to fix the blst problem.

**Comment by bachp** [comment] 2020-12-10 13:51
Currently still an issue on [unstable](https://github.com/sigp/lighthouse/commit/1abc70e815a8dd078b8958450a7516e32cc693cd) with `cargo vendor`:
```
  found duplicate version of package `headers v0.3.2` vendored from two sources:

        source 1: registry `https://github.com/rust-lang/crates.io-index`
        source 2: https://github.com/blacktemplar/headers?branch=lighthouse#8bffbd8a
```

**Comment by blacktemplar** [comment] 2020-12-10 17:41
I think we can close this issue as a duplicate of https://github.com/sigp/lighthouse/issues/1712, at least the three mentioned dependencies are all listed there too.

**Closed** 2021-01-14 18:18 UTC
Labels: A0, t Admin
