### ISSUE TITLE
Design questions regarding PubkeyCache

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1078] opened 2020-04-28 10:48 UTC
I have questions regarding the design of `PubkeyCache` :)

1) **Reads**—When reading the `PubkeyCache` (specifically calling `.get()`) it is important in some situations that the pubkey cache be up to date. There's a bunch of code (e.g. 8 calls to `update_pubkey_cache`, the `PubkeyCacheIncomplete` error in `get_validator_index`) to deal with that. This feels a bit unnecessarily complicated and error prone. For example, what if you forgot to call `update_pubkey_cache` somewhere? Why not do something simpler, e.g. call `update_pubkey_cache` in the only two places where `.get()` is called?
2) **Writes**—When writing to the `PubkeyCache` (specifically calling `.insert()`, which is done only in `update_pubkey_cache`) there seems to be unnecessary checks. Specifically, it seems the `PubkeyCacheInconsistent` error is impossible to trigger. Is that correct?
3) **Timeouts**—The `validator_pubkey` function has a `try_read_for(VALIDATOR_PUBKEY_CACHE_LOCK_TIMEOUT)`. Why doesn't `get_validator_index` have similar timeout logic? Why is there no timeout when doing writes?

**Comment by paulhauner** [comment] 2020-04-28 11:46
> Why not do something simpler, e.g. call update_pubkey_cache in the only two places where .get() is called?

Yep this make sense. I can only put this down to an oversight on my behalf.

> Specifically, it seems the PubkeyCacheInconsistent error is impossible to trigger. Is that correct?

So it might be impossible to trigger this in the broad context of the code-base, however in the specific context of the `PubkeyCache` it has no guarantee that it is fed monotonically increasing indices. I recall adding this a defensive programming feature and given then small overhead of the checks I'm inclined to leave it as-is.

> Why doesn't get_validator_index have similar timeout logic? Why is there no timeout when doing writes?

This timeouts were born out of a time when we were troubleshooting a deadlock. That deadlock turned out to be caused by how we were using our scheduler, not from mutex ordering.

Perhaps we should remove them, but that will require effort that probably provides no performance gains and potentially robs us of some debugging info if we actually do lock something. If I had unlimited time I would probably remove them all, but I'm not sure that's the best use of our time at the moment. Open to a counter argument of course :)

Closing this in favor of #1080. Feel free to re-open if you disagree with anything :)

**Closed by paulhauner** 2020-04-28 11:46 UTC

**Comment by JustinDrake** [comment] 2020-04-29 06:54
> Open to a counter argument of course :)

**Comment by JustinDrake** [comment] 2020-04-29 06:59
> Open to a counter argument of course :)

For a purist like me having consensus critical code be subject to timing assumptions through timeouts feels dirty 😂

> If I had unlimited time I would probably remove them all

I agree with that aspiration :) What about a "good first issue" for this? (I may even try to tackle it myself for fun and bugs.)

**Comment by paulhauner** [comment] 2020-05-01 05:22
@JustinDrake see #1096 :)
