### ISSUE TITLE
Errors from local testnet scripts on MacOS

### ISSUE THREAD

**Issue by pkopparla** [sigp/lighthouse#2763] opened 2021-11-02 08:11 UTC
## Description

The script `lighthouse/scripts/local_testnet/start_local_testnet.sh` does not run and throws errors.

## Version
rustc 1.55.0
Lighthouse v2.0.1-fff01b2, I'm using the stable version.

## Present Behaviour

The script errors out with `./start_local_testnet.sh: eval: line 73: syntax error near unexpected token '>'`

## Expected Behaviour

It should start a local testnet. 

## Steps to resolve

The problem is with line 70 of the script which is currently:
```
CMD="$EX_NAME $@ &>> $LOG_DIR/$LOG_NAME"
```
If you change this to:
```
CMD="$EX_NAME $@ & $LOG_DIR/$LOG_NAME"
```
then the `./start_local_testnet.sh` script will work, however the `./stop_local_testnet.sh` will fail to stop the processes. The PIDS are logged incorrectly in the `PIDS.pid` file within the test directory. Changing the line further to 
``` 
CMD="$EX_NAME $@ &"
```
logs the correct PIDS, though there are still a few unknown PIDS being logged. I don't know if this problem occurs on other OS, but at least one other person can reproduce the problem and solution on their Mac computer.

**Comment by ackintosh** [comment] 2022-01-16 23:51
I'm working on this issue. #2919 

The redirect `&>>` is supported since bash v4 but the version bundled in macOS(11.6.1) is v3.

```bash
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by ackintosh** [comment] 2022-01-27 06:19
@pkopparla https://github.com/sigp/lighthouse/pull/2919 has been merged into `unstable` branch, please give it a try.

**Comment by pkopparla** [comment] 2022-01-27 11:13
@ackintosh Thanks for doing this, I'll check and get back to you.

**Comment by winksaville** [comment] 2022-01-27 18:01
@pkopparla, thanks!

**Comment by pkopparla** [comment] 2022-01-29 07:42
Hey, I just tried this out on `unstable` and it didn't work. This is what happened:
```
local_testnet % ./start_local_testnet.sh 
killing
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

**Comment by michaelsproul** [comment] 2022-01-29 10:47
@pkopparla Which version of macOS?

**Comment by pkopparla** [comment] 2022-01-29 13:20
@michaelsproul It's MacOS Moneterey, v 12.0.1
I'm a fan of your client diversity work, very cool stuff.

**Comment by ackintosh** [comment] 2022-01-29 13:43
I could reproduce the error. 💡 

```bash
# Put PIDS.pid file which contains only newlines.
$ echo "" > ~/.lighthouse/local-testnet/testnet/PIDS.pid

$ ./start_local_testnet.sh
killing
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

As workaround, deleting the PIDS.pid file or running clean.sh could resolve this.

```bash
$ rm ~/.lighthouse/local-testnet/testnet/PIDS.pid
# or
$ ./clean.sh
```

**Comment by ackintosh** [comment] 2022-01-29 13:44
I will file a PR to handle the issue.

**Comment by ackintosh** [comment] 2022-02-01 08:13
https://github.com/sigp/lighthouse/pull/2973 has been merged into `unstable` branch.

**Comment by pkopparla** [comment] 2022-02-01 09:03
@ackintosh I can confirm that the script works now. Thanks for taking time to work on this!

**Closed as completed** 2022-02-01 10:01 UTC
