### ISSUE TITLE
w3s reload of validator pubkeys

### ISSUE THREAD

**Issue by franjoespejo** [sigp/lighthouse#6507] opened 2024-10-17 14:54 UTC
Lighthouse implements the w3signer standard https://lighthouse-book.sigmaprime.io/validator-web3signer.html, but it is unknown when the validator client requests the pubkeys to the w3s. For some w3s implementations, as diva (https://docs.divastaking.net/)  the pubkeys array in the response is changing, therefore it would need the validator client to periodically check the pubkeys the w3s is signing for in order to keep it up to date.

**Comment by michaelsproul** [comment] 2024-10-18 00:48
Closing as duplicate of:

- https://github.com/sigp/lighthouse/issues/2662

**Closed as not planned by michaelsproul** 2024-10-18 00:48 UTC
