### ISSUE TITLE
How to open eth1_deposit_data.rlp

### ISSUE THREAD

**Issue by Greg-Johns** [sigp/lighthouse#1190] opened 2020-05-24 22:22 UTC
I'm on a old iMac, High Sierra and running the validator_client and beacon_node on docker but the Mac OS doesn't recognize the eth1_deposit_data.rlp and I don't know how to get Metamask to kickoff the deposit. Right now opening the file in a browser just shows the public key in the browser window.

How do I get MetaMask to submit the deposit?

**Comment by pawanjay176** [comment] 2020-05-25 14:49
@Greg-Johns you need to be on Goerli network on metamask on this [page](https://lighthouse-book.sigmaprime.io/become-a-validator.html#2-submit-your-deposit-to-goerli) and you should see a "Upload and submit deposit" button on this page.

**Comment by paulhauner** [comment] 2020-06-03 03:38
I believe this was an issue with the encoding of `eth1_deposit_data.rlp` which was fixed in #1193. Please feel free to reopen if the issue is still present :)

**Closed by paulhauner** 2020-06-03 03:38 UTC

**Comment by holiman** [comment] 2022-01-14 13:01
Sorry for reviving a closed issue, but I'm having the same question. I went through the validator key generation described [here](https://lighthouse-book.sigmaprime.io/validator-create.html), for prater testnet. Wound up with the following 
```
$ cat  eth1-deposit-data.rlp
```
``` 
0x22895118000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120ce5316b5fb90bc0bbdcb4ef793bdbbb0a5244be03e59977c3b4d8be349cf51270000000000000000000000000000000000000000000000000000000000000030830dda03a32f90116d61514b141cc3c816a59eb0c26fba0c3ab31e435684e376b4700f35213f2859362a0f3f9ee3f91c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000b8f3eb528e47bdb419f88a873eb4fd92899f476e5ac7f0d465afcbba91185700000000000000000000000000000000000000000000000000000000000000608e697299093b1af8157130b5f44cd210b5290081beead9237d647d5ff2e1c479def32f0fe9a54894f4ac1c7bbdce355f17f98bfd105a7e4aef12c4849767f5114e8ef04bcce10fdaa21ef6bfafbd04f4a3be686803ae002372a971e0b6817d40
```
Which is not valid a rlp structure.

**Comment by holiman** [comment] 2022-01-14 13:08
Ah. So, although it's called `.rlp`, it's actually hex-encoded ABI data, not rlp. That explains it. 

```
~/go/src/github.com/ethereum/go-ethereum/cmd/abidump/abidump  0x22895118000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120ce5316b5fb90bc0bbdcb4ef793bdbbb0a5244be03e59977c3b4d8be349cf51270000000000000000000000000000000000000000000000000000000000000030830dda03a32f90116d61514b141cc3c816a59eb0c26fba0c3ab31e435684e376b4700f35213f2859362a0f3f9ee3f91c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000b8f3eb528e47bdb419f88a873eb4fd92899f476e5ac7f0d465afcbba91185700000000000000000000000000000000000000000000000000000000000000608e697299093b1af8157130b5f44cd210b5290081beead9237d647d5ff2e1c479def32f0fe9a54894f4ac1c7bbdce355f17f98bfd105a7e4aef12c4849767f5114e8ef04bcce10fdaa21ef6bfafbd04f4a3be686803ae002372a971e0b6817d40 
Info: Transaction invokes the following method: "deposit(bytes: [131 13 218 3 163 47 144 17 109 97 81 75 20 28 195 200 22 165 158 176 194 111 186 12 58 179 30 67 86 132 227 118 180 112 15 53 33 63 40 89 54 42 15 63 158 227 249 28],bytes: [0 184 243 235 82 142 71 189 180 25 248 138 135 62 180 253 146 137 159 71 110 90 199 240 212 101 175 203 186 145 24 87],bytes: [142 105 114 153 9 59 26 248 21 113 48 181 244 76 210 16 181 41 0 129 190 234 217 35 125 100 125 95 242 225 196 121 222 243 47 15 233 165 72 148 244 172 28 123 189 206 53 95 23 249 139 253 16 90 126 74 239 18 196 132 151 103 245 17 78 142 240 75 204 225 15 218 162 30 246 191 175 189 4 244 163 190 104 104 3 174 0 35 114 169 113 224 182 129 125 64],bytes32: [206 83 22 181 251 144 188 11 189 203 78 247 147 189 187 176 165 36 75 224 62 89 151 124 59 77 139 227 73 207 81 39])"

```
