### ISSUE TITLE
BeaconAPI Spec Conformance

### ISSUE THREAD

**Issue by z3n-chada** [sigp/lighthouse#3220] opened 2022-05-25 15:42 UTC
## Description

Issues with spec conformance for BeaconAPI json-rpc endpoint.

## Version
unstable

## Expected Behaviour
| API Path                                              | Inputs | Issue                         |
|:----------------------------------------------------- |:------ |:----------------------------- |
| /eth/v1/beacon/states/(state)/root                    | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/fork                 | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/finality_checkpoints | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/validators           | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/committees           | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/sync_committees      | "head" | No execution_optimistic field |
| /eth/v1/beacon/headers                                | "head" | No execution_optimistic field |
| /eth/v1/node/syncing                                  | None   | No is_optimistic field        |

## Steps to resolve
See above.

**Comment by michaelsproul** [comment] 2022-05-27 04:43
We're aware of this and have an open PR to implement this here: https://github.com/sigp/lighthouse/pull/3070.

Closing as a duplicate of https://github.com/sigp/lighthouse/issues/3031

**Closed as completed by michaelsproul** 2022-05-27 04:43 UTC
Labels: duplicate
