### ISSUE TITLE
Memory Leaks and OOM

### ISSUE THREAD

**Issue by rayn316** [sigp/lighthouse#6663] opened 2024-12-06 07:51 UTC
## Description

Please provide a brief description of the issue.
Sudden increase in memory causes OOM

## Version

Please provide your Lighthouse and Rust version. Are you building from
`stable` or `unstable`, which commit?
stable: v6.0.0

## Present Behaviour

Describe the present behaviour of the application, with regards to this
issue.

Memory usage increases suddenly and continuously over several minutes with no error messages in the logs
<img width="608" alt="image" src="https://github.com/user-attachments/assets/d040d5ea-8e29-4fad-a287-182965004a9d">

## Expected Behaviour

How _should_ the application behave?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment] 2024-12-06 08:36
Tell us a bit more:

- Hardware specs, especially the SSD is relevant. If your disk isn't keeping up with writes they will get queued up and use a lot of memory.
- Flags you're using. Some relevant ones could be `--disable-backfill-rate-limiting`, `--slasher`, `--reconstruct-historic-states`, `--prune-blobs`.
- Are there any indexing services or other applications making calls to the HTTP API? What about a connected validator client?

If you can also share debug logs they will help us look into it. You can find them in `$datadir/beacon/logs`. You can compress them and DM them to me on Discord where I am `@sproul`.

**Comment by michaelsproul** [comment] 2024-12-06 08:38
The blob pruning flag could be relevant if you were using `--prune-blobs false` in the past and turned it back on:

- https://github.com/sigp/lighthouse/issues/6559

**Comment by rayn316** [comment] 2024-12-06 08:42
run cmd: 
```
/node/archive/ethereum/bin/lighthouse bn -d /node/archive/ethereum/lighthouse --network mainnet --execution-endpoint 'http://127.0.0.1:21303' --execution-jwt '/node/archive/ethereum/erigon/jwt.hex' --checkpoint-sync-url=https://sync-mainnet.beaconcha.in --port 21309 --http --http-port 21307 --http-address 0.0.0.0 --http-allow-origin='*'
```

The disk is nvme, the write speed is OK, and the record does not reach the write speed limit.

**Comment by michaelsproul** [comment] 2024-12-06 08:57
@ryan316 Ok, those flags look fine. It might be that your DB is corrupt. Can you show me output from:

```
curl http://localhost:21307/lighthouse/database/info
```

**Comment by rayn316** [comment] 2024-12-06 09:00
```
{
  "schema_version": 22,
  "config": {
    "block_cache_size": 5,
    "state_cache_size": 128,
    "compression_level": 1,
    "historic_state_cache_size": 1,
    "hdiff_buffer_cache_size": 16,
    "compact_on_init": false,
    "compact_on_prune": true,
    "prune_payloads": true,
    "hierarchy_config": {
      "exponents": [
        5,
        9,
        11,
        13,
        16,
        18,
        21
      ]
    },
    "prune_blobs": true,
    "epochs_per_blob_prune": 1,
    "blob_prune_margin_epochs": 0
  },
  "split": {
    "slot": "10547392",
    "state_root": "0x5f03e87e244373c3bcb5eda29d59fa68803a9d7cc1548757fc6e080218846b97",
    "block_root": "0xd2b3a980b8513f3fedd0353fefb185d5a1d23c039857360a54c0f9b259ff8b63"
  },
  "anchor": {
    "anchor_slot": "0",
    "oldest_block_slot": "0",
    "oldest_block_parent": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "state_upper_limit": "18446744073709551615",
    "state_lower_limit": "0"
  },
  "blob_info": {
    "oldest_blob_slot": "9346560",
    "blobs_db": true
  }
}
```

**Comment by rayn316** [comment] 2024-12-06 09:04
So the solution now is to add this parameter `--prune-blobs false` ?  @michaelsproul

**Comment by michaelsproul** [comment] 2024-12-06 09:05
> So the solution now is to add this parameter --prune-blobs false ?

No. That issue relates to a bug with that flag. Adding it won't help.

**Comment by michaelsproul** [comment] 2024-12-06 09:07
Your database metadata looks good. The `split.slot` is not too old, so you're unlikely to be effected by database corruption.

Please send debug logs, as I think I've ruled out all the low-hanging issues

**Comment by michaelsproul** [comment] 2024-12-06 09:08
How much RAM does your machine have?

**Comment by rayn316** [comment] 2024-12-06 09:16
RAM: 128G

OOM Time: 08:48:22
[beacon.log](https://github.com/user-attachments/files/18035656/beacon.log)

**Comment by rayn316** [comment] 2024-12-06 09:20
Memory usage graph
<img width="609" alt="image" src="https://github.com/user-attachments/assets/97f58ec3-aee7-4110-b718-f9dae206c548">

Disk IO and read/write speeds
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/38dda9df-8b2d-4837-8eb5-a75ba276a5bb">

**Comment by michaelsproul** [comment] 2024-12-06 09:48
Does Lighthouse get auto-restarted when it OOMs, or are you restarting it manually? I noticed there's a long gap between the OOM and when it starts again:

> Dec 06 08:42:28.013 DEBG Invalid attestation from network, type: "aggregated", peer_id: 16Uiu2HAmMop2oPuk45Qdfvg8wShW1cXxgTGAyYtnLtKeECi1EzNK, block: 0x03c042b26a587041457b6a107ac65ec2758c828bc38f10a48d1c15fd26fd3973, reason: PastSlot { attestation_slot: Slot(10554171), earliest_permissible_slot: Slot(10554176) }, module: network::network_beacon_processor::gossip_methods:2702
> Dec 06 08:48:22.351 INFO Logging to file, path: "/node/archive/ethereum/lighthouse/beacon/logs/beacon.log", module: environment:311
> Dec 06 08:48:22.358 INFO Lighthouse started, version: Lighthouse/v6.0.0-c042dc1, module: lighthouse:680

Is the OOM-killer log from 08:48:22? That would imply Lighthouse was doing something without logging anything for 6 minutes from 08:42 to 08:48. That would be very strange. This also corresponds to the period with no metrics in your graphs

**Comment by michaelsproul** [comment] 2024-12-06 09:53
Is that memory usage metric for Lighthouse or the whole machine, because I noticed that Erigon is also unhappy around 08:38 and this could have been what kicked off the whole process:

> Dec 06 08:38:37.672 WARN Execution engine call failed, error: HttpClient(url: http://127.0.0.1:21303/, kind: timeout, detail: operation timed out), service: exec, module: execution_layer::engines:398

**Comment by rayn316** [comment] 2024-12-06 09:59
The erigon memory usage is stable and there are no sudden states.
The reason why there is no task record in the middle is that the memory is full and cannot respond. There is no record until the system kills the lighthouse program to release the memory space. And lighthouse is set to restart automatically, so it will automatically start after being killed.

**Comment by rayn316** [comment] 2024-12-06 10:03
And the strange thing is that the memory problem only occurs on eth mainnet, speolia and holesky do not have this problem
Maybe this is a problem that only occurs when running with erigon, it works fine on the geth node

**Comment by rayn316** [comment] 2024-12-06 10:08
I will try to delete all data and run again to generate full v6.0.0 data

**Comment by rayn316** [comment] 2024-12-06 10:28
Now it seems that Lighthouse is stable. This may be caused by the large amount of data in version v5. There is no memory increase after regenerating the Lighthouse data. @michaelsproul
```
du -h -d 0 ./* 2>/dev/null
308M	./bin
3.0T	./erigon
729G	./lighthouse
```

**Comment by michaelsproul** [comment] 2024-12-06 10:43
Hmm interesting. Can you give a breakdown of the contents of the lighthouse dir, i.e. the sizes of chain_db and freezer_db?

There's an issue I'm aware of where Lighthouse won't immediately compact the freezer after pruning historic states. That is probably leading to a large freezer DB, and possibly high memory usage when LevelDB tries to write to that DB (just a guess).

I've been planning to open a PR to make Lighthouse compact the freezer more aggressively

**Comment by rayn316** [comment] 2024-12-06 12:42
`--reconstruct-historic-states --historic-state-cache-size 4 --disable-backfill-rate-limiting --prune-blobs=false --disable-upnp`
The directory information can no longer be viewed, but it was running in archive mode for a while before, and then it was restored to normal mode, so it is so large

**Comment by michaelsproul** [comment] 2024-12-06 22:58
@rayn316 Those are the flags you were using before?

Then this _is_ an instance of the prune blobs bug:

- https://github.com/sigp/lighthouse/issues/6559

Basically your database was full of blobs and Lighthouse was trying to load them all into memory in order to delete them, which causes the OOM. We are working on a fix for this that involves pruning blob without loading them into memory.

**Comment by michaelsproul** [comment] 2024-12-07 01:40
Closing as duplicate of #6559

**Closed as not planned by michaelsproul** 2024-12-07 01:40 UTC
Labels: question
