### ISSUE TITLE
parse error on validators REST endpoint

### ISSUE THREAD

**Issue by AdvancedStyle** [sigp/lighthouse#1622] opened 2020-09-15 19:20 UTC
## Description

Get errors when querying the validators REST api (https://lighthouse-book.sigmaprime.io/http/validator.html)

## Version

Lighthouse/v0.2.9-e5fc6bab/x86_64-linux

## Present Behaviour

```# curl -s "localhost:5052/validator/duties/all"```

Results in:

```parse error: Invalid numeric literal at line 1, column 4```

## Expected Behaviour

All the other (non validator) endpoints seem to work as normal and return JSON; I would expect this to return some JSON too.

**Comment by michaelsproul** [comment] 2020-09-16 01:18
I couldn't reproduce this. Did you provide an `epoch` parameter?

```
curl -s "http://localhost:5052/validator/duties/all?epoch=9565" > all_duties.json
```

**Comment by AdvancedStyle** [comment] 2020-09-16 07:35
Yes that works i was missing the epoch parameter (maybe error message should indicate that)

**Comment by michaelsproul** [comment] 2020-09-16 08:35
We're moving to a new (standardised 😯) API soon which will have nicer errors. Thanks for the report!

**Closed** 2020-09-16 08:35 UTC
Labels: A1, t API
