### ISSUE TITLE
How to solve WARN Execution endpoint is not synced?

### ISSUE THREAD

**Issue by Gessi12** [sigp/lighthouse#5312] opened 2024-02-26 13:39 UTC
## Description

WARN Execution endpoint is not synced        last_seen_block_unix_timestamp: 1704111816, endpoint:xxxxxx auth=true, service: deposit_contract_rpc

## Version

Please provide your Lighthouse and Rust version. Are you building from
lighthouse `stable` 
erigon /2.58.0

## Present Behaviour
Sepolia's block is stuck at 4999999

![微信图片_20240227104103](https://github.com/sigp/lighthouse/assets/85423716/dafdb770-fbd3-4fd3-992b-37df82197097)

![微信图片_20240227103748](https://github.com/sigp/lighthouse/assets/85423716/b5c29594-17ae-496e-90cd-621ad1c9fe1f)

**Comment by chong-he** [comment] 2024-02-26 23:31
The warning log means that both CL and EL are syncing. It looks like you have very low peer count on the CL, you can try to port forwarding the ports to increase peer count and that should help it to sync.

**Comment by Gessi12** [comment] 2024-02-26 23:55
> The warning log means that both CL and EL are syncing. It looks like you have very low peer count on the CL, you can try to port forwarding the ports to increase peer count and that should help it to sync.

Thank you, I will try. However, a few days ago, there was no such issue. I'm not sure if there was any problem with the lighthouse

**Comment by chong-he** [comment] 2024-02-27 00:58
> > The warning log means that both CL and EL are syncing. It looks like you have very low peer count on the CL, you can try to port forwarding the ports to increase peer count and that should help it to sync.
> 
> Thank you, I will try. However, a few days ago, there was no such issue. I'm not sure if there was any problem with the lighthouse

A few days ago it was synced? How was the peer count back then? It could be the drop in peer count that causes it to fall out of sync. Are you on Lighthouse v5.0.0?

**Comment by Gessi12** [comment] 2024-02-27 02:45
> > > The warning log means that both CL and EL are syncing. It looks like you have very low peer count on the CL, you can try to port forwarding the ports to increase peer count and that should help it to sync.
> > 
> > 
> > Thank you, I will try. However, a few days ago, there was no such issue. I'm not sure if there was any problem with the lighthouse
> 
> A few days ago it was synced? How was the peer count back then? It could be the drop in peer count that causes it to fall out of sync. Are you on Lighthouse v5.0.0?

4.6.0

**Comment by Gessi12** [comment] 2024-02-27 03:37
> > > The warning log means that both CL and EL are syncing. It looks like you have very low peer count on the CL, you can try to port forwarding the ports to increase peer count and that should help it to sync.
> > 
> > 
> > Thank you, I will try. However, a few days ago, there was no such issue. I'm not sure if there was any problem with the lighthouse
> 
> A few days ago it was synced? How was the peer count back then? It could be the drop in peer count that causes it to fall out of sync. Are you on Lighthouse v5.0.0?

Changing to the latest version is the same, low peer count. How to port forwarding the ports to increase peer count

**Comment by chong-he** [comment] 2024-02-27 09:04
How to open ports: https://lighthouse-book.sigmaprime.io/advanced_networking.html#how-to-open-ports

Do you have peer count in the execution client?

When you say there was no issue few days ago, could you check how was the peer count back then? 

What is the hardware spec?

**Comment by Gessi12** [comment] 2024-02-27 09:15
> How to open ports: https://lighthouse-book.sigmaprime.io/advanced_networking.html#how-to-open-ports
> 
> Do you have peer count in the execution client?
> 
> When you say there was no issue few days ago, could you check how was the peer count back then?
> 
> What is the hardware spec?

CentOS Linux release 7.9.2009
cpu: 4
memory: 16G
ssd disk: 500G

**Comment by chong-he** [comment] 2024-02-27 09:17
Hardware specs is ok. Check how much disk space left just in case, Sepolia doesn't use a lot of disk space

Also look for this:
> When you say there was no issue few days ago, could you check how was the peer count back then?

Because there is a report here about peer loss over time: https://github.com/sigp/lighthouse/issues/5271
See if this is your case. If so, some debug logs will be helpful to troubleshoot

**Comment by chong-he** [comment] 2024-03-12 14:56
@Gessi12 Do you run your node locally or using a VPS? Recently we see some low peer issues with a VPS. If you are using a VPS, that may be the cause.

**Comment by Gessi12** [comment] 2024-03-13 06:01
> @Gessi12 Do you run your node locally or using a VPS? Recently we see some low peer issues with a VPS. If you are using a VPS, that may be the cause.

VPS

**Comment by chong-he** [comment] 2024-03-13 08:05
> > @Gessi12 Do you run your node locally or using a VPS? Recently we see some low peer issues with a VPS. If you are using a VPS, that may be the cause.
> 
> VPS

Any chance it is Contabo? If so, then it is the VPS issue.
The solution is to change the port by adding `--port` in the beacon node. Any port other than 9000 is good.

**Comment by chong-he** [comment] 2024-03-18 08:28
@Gessi12 Is the problem solved? We could close this issue if it is solved now, thanks

**Comment by Gessi12** [comment] 2024-03-18 08:31
> @Gessi12 Is the problem solved? We could close this issue if it is solved now, thanks
yes

**Closed as completed** 2024-03-18 08:36 UTC
Labels: question
