### ISSUE TITLE
Run image as non-root

### ISSUE THREAD

**Issue by jmcruz1983** [sigp/lighthouse#2971] opened 2022-01-28 19:02 UTC
## Description

Current docker image runs as root user as default.
```
docker run -it sigp/lighthouse:v2.1.1 sh
# id
uid=0(root) gid=0(root) groups=0(root)
```
I would suggest to add a custom user to avoid to run as root as recommended by best practices.

**Comment by michaelsproul** [comment] 2022-01-28 22:50
Closing as a duplicate of https://github.com/sigp/lighthouse/issues/1905

**Closed as completed by michaelsproul** 2022-01-28 22:50 UTC
