### ISSUE TITLE
StateRootMismatch while syncing on windows 

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#2134] opened 2020-12-31 10:06 UTC
## Description

Seeing syncing issues with nodes running on vms on top of windows. Syncs fine for a while and then stops with 
`DEBG Invalid block received                  outcome: StateRootMismatch`

Checking further, it looks like we get the state mismatch because the `randao_mixes` in the state on which the block was being applied to was different than the canonical state by a bit. So it looks to me like some sort of data corruption in the existing state, not sure what caused it.

Seen 2 instances of this issue.
1. Ubuntu 20.04 VM on WSL.
2. Ubuntu 20.04 VM on top of hypervisor with windows server host.

## Version

Lighthouse v1.0.4

**Comment by clifton** [comment] 2021-01-31 00:29
This happened to me on ubtuntu 18.04 in wsl2 in a docker container twice (once about a month ago and again this morning)

**Comment by michaelsproul** [comment] 2022-05-18 07:12
Closing as duplicate of #3011

**Closed by michaelsproul** 2022-05-18 07:12 UTC
Labels: bug, windows
