### ISSUE TITLE
Unsolicited UDP packets coming from Lighthouse Node

### ISSUE THREAD

**Issue by jrhea** [sigp/lighthouse#1145] opened 2020-05-13 21:59 UTC
## Description

i noticed that the IP address [redacted] has been sending me unsolicited UDP packets.  I did a whois and got:

```
AS      | IP               | BGP Prefix          | CC | Registry | Allocated  | AS Name
16509   | xxxxxx    | xxxxx       | US | arin     | 2018-06-29 | AMAZON-02, US
```
Using some data that I collected from crawling testnet DHTs, I was able to match the IP address to nodeid: `02daa24c13fd5e4dbdbba9bc866b38e182cfbc0e16f4deecd64275e912fd55c8`
which is a Lighthouse node that @protolambda runs.

Things to note:
- I have no clients or crawlers currently running so my machine replies with an ICMP packet to notify the sender that the port is unreachable 
- I noticed that the UDP packet data has a prefix that alternates between two hex values and if i take the time difference between packets with matching prefixes....it is 300 seconds.  Coincidentally, 300 default value that lighthouse uses for the discv5 config param `ping_interval`.

https://github.com/sigp/lighthouse/blob/637ba8120b95adc508f40899d5415d5dc77e5b89/beacon_node/eth2-libp2p/src/config.rs#L120

I realize the evidence is circumstantial, but it seemed worth noting.   I'm wondering if this is some weird edge case that one of my crawlers triggered and now this node is stuck in a state where it is calling send_ping() every 300 seconds.  If needed, I can provide a packet capture to help diagnose.

**Comment by AgeManning** [comment] 2020-05-18 11:47
I have made changes to discv5. However I could not reproduce this. 

I suspect these are packets coming from other nodes who are checking if this peer is still alive. The packets you were receiving were encrypted, so i could not determine their contents. Discv5 modifications will now terminate a session for a dead node, so these will now be unencrypted, and I suspect will be random packets of other nodes trying to establish or find more peers in a small DHT. 

I will close this for now, but it will be interesting to continue to track as we continue with testnets.

**Closed by AgeManning** 2020-05-18 11:47 UTC

**Comment by jrhea** [comment] 2020-05-18 12:25
Is this the PR that contains the changes u made?

https://github.com/sigp/discv5/pull/9

**Comment by AgeManning** [comment] 2020-05-18 13:00
Yep
