### ISSUE TITLE
No data saved by beacon node without --datadir parameter

### ISSUE THREAD

**Issue by ghost** [sigp/lighthouse#1939] opened 2020-11-20 17:12 UTC
## Description

When I run beacon node with docker and haven't supplied --datadir parameter to lighthouse, It didn't create beacon directory thus not saving it's state. There was only validator directory inside /root/.lighthouse/pyrmont

## Version

version v0.3.5-7e4ee587 build for docker from source

## Present Behaviour

Lighthouse is not creating beacon directory without specifying --datadir manually.

## Expected Behaviour

It should create beacon directory with chaindata inside.

**Comment by paulhauner** [comment] 2020-11-23 01:00
> When I run beacon node with docker and haven't supplied --datadir parameter to lighthouse, It didn't create beacon directory thus not saving it's state. There was only validator directory inside /root/.lighthouse/pyrmont

Could you please share the command you used `--datadir` with please? E.g., `lighthouse bn ...` or `lighthouse account ...`.

**Comment by 0xf1d0** [comment] 2020-11-23 07:13
With this command it didn't work:
```
docker run -d \
        --name beacon \
        --network host \
        --restart always \
        -v $(pwd)/.lighthouse:/root/.lighthouse \
        lighthouse:local \
        lighthouse --testnet pyrmont bn --target-peers 20 --metrics --disable-upnp --staking --http-address 127.0.0.1
```
With this it works:
```
docker run -d \
	--name beacon \
	--network host \
	--restart always \
	-v $(pwd)/.lighthouse:/root/.lighthouse \
	lighthouse:local \
	lighthouse --testnet pyrmont bn --target-peers 20 --metrics --datadir /root/.lighthouse/pyrmont --disable-upnp --staking --http-address 127.0.0.1
```

**Comment by realbigsean** [comment] 2021-01-14 19:03
I can't reproduce this, so going to close it

**Closed by realbigsean** 2021-01-14 19:03 UTC
Labels: A0, bug
