### ISSUE TITLE
Unable to sync beacon node after hard reset.

### ISSUE THREAD

**Issue by notrelatedtoanyone** [sigp/lighthouse#3044] opened 2022-02-27 20:32 UTC
## Description

After a period of downtime, I am unable to sync again. I have already tried purging the database and will try once more. 

In the logs, I am seeing the following (after purging the db once already):
```
Feb 27 20:22:13.110 DEBG Missed snapshot cache                   block_delay: None, parent_root: 0x1dcad0c39f03315bb8da182b0d571bd5f7087121e3e5076568ae205b85adbaf7, parent_slot: 1687714, slot: 1687715, service: beacon
Feb 27 20:22:13.646 DEBG Invalid block received                  outcome: StateRootMismatch { block: 0xe97dda6d6b914cabf49423136b68b2f4c74d7e0d5c9f56b6076157b0787e51fb, local: 0x196c4124b648df1b8f70adb24618c2fb08ae44562efa2227c47cf3b81768d81e }, msg: peer sent invalid block
Feb 27 20:22:13.646 DEBG Batch processing failed                 service: sync, error: Peer sent invalid block. Reason: StateRootMismatch { block: 0xe97dda6d6b914cabf49423136b68b2f4c74d7e0d5c9f56b6076157b0787e51fb, local: 0x196c4124b648df1b8f70adb24618c2fb08ae44562efa2227c47cf3b81768d81e }, imported_blocks: 0, last_block_slot: 1687776, chain: 171210342189190087, first_block_slot: 1687714, batch_epoch: 52741
Feb 27 20:22:13.646 DEBG Batch processing failed                 client: Prysm: version: e26cde5e091befe0c777992734c37e7a1e6c53c2, os_version: unknown, peer: 16Uiu2HAm3DcU6FztNfXnuRLsQm3Es9rvWPS7TuZXrZ7zykn1SZbX, batch_epoch: 52741, imported_blocks: false, chain: 171210342189190087, service: sync
Feb 27 20:22:13.646 WARN Batch failed to download. Dropping chain scoring peers, batch_epoch: 52741, score_adjustment: None, chain: 171210342189190087, service: sync
Feb 27 20:22:13.647 DEBG Chain removed                           op: batch processing result, reason: ChainFailed(Epoch(52741)), id: 171210342189190087, from: 52739, to: 102001, end_root: 0xad5c…bdaa, current_target: 52741, batches: 7, peers: 9, validated_batches: 0, state: Syncing, sync_type: Finalized, service: sync
```

## Version

stable, lastest version.

## Present Behaviour

Beacon node is unable to sync, 

## Expected Behaviour

Beacon node is able to sync.

## Steps to resolve

No clue.

**Comment by michaelsproul** [comment] 2022-02-27 21:09
Sorry to hear you're having issues. If the DB corruption is happening consistently it could be an issue with the RAM or disk in your machine. Please try running a memory test using memtest86+ (it comes with most linux live distros).

We're also aware of one bug in the DB code that can cause corruption occasionally (https://github.com/sigp/lighthouse/issues/3011), but if you use checkpoint sync and _don't_ use `--reconstruct-historic-states` then it should be unlikely that you encounter it repeatedly. Which flags are you using to start the BN?

**Comment by michaelsproul** [comment] 2022-05-18 07:00
Closing as duplicate of #3011

**Closed as completed by michaelsproul** 2022-05-18 07:00 UTC
