### ISSUE TITLE
Lighthouse won't start

### ISSUE THREAD

**Issue by memsido** [sigp/lighthouse#2895] opened 2022-01-10 07:42 UTC
## Description

The service keeps restarting. My server's had a crash, it seemes to have corrupted the DB.

## Version
Lighthouse v2.0.1
rustc 1.54.0
 
## Present Behaviour

failed to build beacon chain: Error writing chain & metadata to disk: DBError
message: corruption: bad block type

Any ideas? Should I try to rebuild the DB?

**Comment by michaelsproul** [comment] 2022-01-10 08:26
> Any ideas? Should I try to rebuild the DB?

Yes. You should resync using checkpoint sync and the `--purge-db` flag (or delete the database directory manually).

https://lighthouse-book.sigmaprime.io/checkpoint-sync.html

Sometimes power outages can cause this sort of corruption. There's not much we can do about it in Lighthouse as this is mostly a property of LevelDB.

**Comment by memsido** [comment] 2022-01-10 08:48
Yeah, I was worried that might be it. The sync is up and running, hopefully will be back in about a day. 
Thank you

**Comment by memsido** [comment] 2022-01-10 09:11
I would like to do resync using the checkpoint sync. 
I purged the DB `lighthouse bn --purge-db` but that seems to have started sync from genesis block. Can I stop it?

**Comment by michaelsproul** [comment] 2022-01-10 10:58
> I purged the DB lighthouse bn --purge-db but that seems to have started sync from genesis block. Can I stop it?

Yep. If you want to do checkpoint sync just add both flags `lighthouse bn --purge-db --checkpoint-sync-url X`. Then remove the `--purge-db` flag once you've synced

**Comment by michaelsproul** [comment] 2022-01-17 02:19
Closing this because I think we found the root cause of @memsido's issue

**Closed as completed by michaelsproul** 2022-01-17 02:19 UTC
