### ISSUE TITLE
FailedToInsertDeposit

### ISSUE THREAD

**Issue by MysticRyuujin** [sigp/lighthouse#1209] opened 2020-05-27 14:09 UTC
## Description

I receive this error in my logs, over and over:
```
{
  "msg": "Failed to update eth1 cache",
  "level": "ERRO",
  "ts": "2020-05-27T09:02:20.147080658-05:00",
  "service": "eth1_rpc",
  "error": "Failed to update eth1 cache: FailedToInsertDeposit(NonConsecutive { log_index: 52, expected: 51 })",
  "retry_millis": "7000"
}

```
I run lighthouse with the following command:
`/home/lighthouse/.cargo/bin/lighthouse --logfile /data/lighthouse/logs/beacon.log beacon_node --eth1 --http --ws --datadir /data/lighthouse --http-address 0.0.0.0 --ws-address 0.0.0.0`

I run a Nethermind eth1 client, archive sync to Goerli, version `1.8.40`

I will say that this is as far as I got, I'm not running a validator yet. I wanted the beacon node to be up and running and in sync before I moved on to the next steps...

## Version

`Lighthouse 0.1.2`

## Present Behaviour

It's not clear to me what this log means, I searched for it but I couldn't find it.

## Expected Behaviour

Unknown

**Comment by paulhauner** [comment] 2020-05-28 01:02
This is interesting.. it means that it's not getting the deposit logs in order. It's possible if the eth1 client undergoes a deep re-org, but that seems unlikely.

If you run `rm -r ~/.lighthouse/beacon` does the same error occur? It would be interesting to know if this is a one-off or a recurring issue.

**Comment by MysticRyuujin** [comment] 2020-05-28 01:12
I stopped the beacon node, deleted the beacon folder, restarts the service and yes, I get the same error.

It may have something to do with Nethermind?

**Comment by MysticRyuujin** [comment] 2020-05-28 01:14
Here is the log:

```
{"msg":"Block production enabled","level":"INFO","ts":"2020-05-27T20:11:13.486646953-05:00","method":"json rpc via http","endpoint":"http://localhost:8545"}
{"msg":"WebSocket server started","level":"INFO","ts":"2020-05-27T20:11:13.487098007-05:00","service":"ws","port":5053,"address":"0.0.0.0"}
{"msg":"Beacon chain initialized","level":"INFO","ts":"2020-05-27T20:11:13.495261544-05:00","service":"beacon","head_slot":"0","head_block":"0x19aa…ba12","head_state":"0x773c…5b17"}
{"msg":"Libp2p Service","level":"INFO","ts":"2020-05-27T20:11:13.496084075-05:00","service":"libp2p","peer_id":"PeerId(\"QmTPVwiJAFStALq7Frd3mT99yQryiToZcZR5LqG8ZvV7Ui\")"}
{"msg":"ENR Initialised","level":"INFO","ts":"2020-05-27T20:11:13.496309397-05:00","service":"libp2p","tcp":"Some(9000)","udp":"None","ip":"None","id":"0x502a..cfc4","seq":1,"enr":"enr:-KO4QHBfsRzu3C_zWagOn4gHQBWHziUHsnKVqaCEGgtc5P16Y8N7ckz6uN_AVFdO6xjRoQEZWg1ckEBQJ2mghWeGCO8Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD2d10HAAABE___________gmlkgnY0iXNlY3AyNTZrMaECZGY2e7khYwWXaU7R4j2jwjSCzDgcPAU44Z1uKkbnK4-DdGNwgiMo"}
{"msg":"Listening established","level":"INFO","ts":"2020-05-27T20:11:13.496855599-05:00","service":"libp2p","address":"/ip4/0.0.0.0/tcp/9000/p2p/16Uiu2HAm2Bb9VqCx52R94o3B9HTAhXkhYTBWS1Th2uZADa843jGa"}
{"msg":"Subscribed to topics","level":"INFO","ts":"2020-05-27T20:11:13.496905827-05:00","service":"libp2p","topics":"[BeaconBlock, BeaconAggregateAndProof, VoluntaryExit, ProposerSlashing, AttesterSlashing]"}
{"msg":"HTTP API started","level":"INFO","ts":"2020-05-27T20:11:13.497367291-05:00","service":"http","port":5052,"address":"0.0.0.0"}
{"msg":"Failed to update eth1 cache","level":"ERRO","ts":"2020-05-27T20:11:13.785853059-05:00","service":"eth1_rpc","error":"Failed to update eth1 cache: FailedToInsertDeposit(NonConsecutive { log_index: 52, expected: 51 })","retry_millis":"7000"}
```

**Comment by paulhauner** [comment] 2020-05-28 01:39
> It may have something to do with Nethermind?

I do suspect this is the case. @pawanjay176, do I recall you having Lighthouse working on Nethermind. I know there's an issue about headers with Nethermind, but I don't think it looks like this.

**Comment by MysticRyuujin** [comment] 2020-05-28 01:44
Is there a JSON RPC command I can send directly to Nethermind to grab the output from? See how it's behaving?

**Comment by MysticRyuujin** [comment] 2020-05-28 01:50
Actually JSON RPC logging is on in Nethermind. I see this over and over:

```
2020-05-27 20:49:22.5108|INFO|6|Executing JSON RPC call eth_getlogs with params {
  "address": "0x42cc0fceb02015f145105cf6f19f90e9bea76558",
  "fromBlock": "0x2a310a",
  "toBlock": "0x2a34f2",
  "topics": [
    "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
  ]
}
2020-05-27 20:49:22.5188|INFO|96|Executing JSON RPC call eth_getlogs with params {
  "address": "0x42cc0fceb02015f145105cf6f19f90e9bea76558",
  "fromBlock": "0x2a34f2",
  "toBlock": "0x2a38da",
  "topics": [
    "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
  ]
}
2020-05-27 20:49:22.5264|INFO|11|Executing JSON RPC call eth_getlogs with params {
  "address": "0x42cc0fceb02015f145105cf6f19f90e9bea76558",
  "fromBlock": "0x2a38da",
  "toBlock": "0x2a3cc2",
  "topics": [
    "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
  ]
}
2020-05-27 20:49:22.5347|INFO|19|Executing JSON RPC call eth_getlogs with params {
  "address": "0x42cc0fceb02015f145105cf6f19f90e9bea76558",
  "fromBlock": "0x2a3cc2",
  "toBlock": "0x2a40aa",
  "topics": [
    "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
  ]
}
2020-05-27 20:49:22.5423|INFO|98|Executing JSON RPC call eth_getlogs with params {
  "address": "0x42cc0fceb02015f145105cf6f19f90e9bea76558",
  "fromBlock": "0x2a40aa",
  "toBlock": "0x2a4492",
  "topics": [
    "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
  ]
}
2020-05-27 20:49:22.5648|INFO|12|Executing JSON RPC call eth_getlogs with params {
  "address": "0x42cc0fceb02015f145105cf6f19f90e9bea76558",
  "fromBlock": "0x2a4492",
  "toBlock": "0x2a487a",
  "topics": [
    "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
  ]
}
2020-05-27 20:49:22.5726|INFO|13|Executing JSON RPC call eth_getlogs with params {
  "address": "0x42cc0fceb02015f145105cf6f19f90e9bea76558",
  "fromBlock": "0x2a487a",
  "toBlock": "0x2a4c62",
  "topics": [
    "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
  ]
}
2020-05-27 20:49:22.5807|INFO|12|Executing JSON RPC call eth_getlogs with params {
  "address": "0x42cc0fceb02015f145105cf6f19f90e9bea76558",
  "fromBlock": "0x2a4c62",
  "toBlock": "0x2a4ca5",
  "topics": [
    "0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"
  ]
}
```

**Comment by tkstanczak** [comment] 2020-05-28 02:13
@paulhauner nice to meet you, would you be able to hint at the problem with headers?
Also when you say the deposits are not coming in order, what do you mean there?

**Comment by paulhauner** [comment] 2020-05-28 04:42
Hi @tkstanczak, nice to meet you too!

> would you be able to hint at the problem with headers?

I haven't been following these issues, so I'm a bit behind sorry. I thought there was an issue with Nevermind headers, but perhaps I'm mistaken. I know there's an issue here that we were dealing with: https://github.com/NethermindEth/nethermind/issues/1958.

I might leave this up to @pawanjay176 since he has more knowledge here :)

> Also when you say the deposits are not coming in order, what do you mean there?

The [eth2 deposit contract](https://github.com/ethereum/eth2.0-specs/blob/dev/deposit_contract/contracts/validator_registration.vy) should be creating logs which have an always-increasing-by-one `deposit_count`. The error we're getting (`FailedToInsertDeposit(NonConsecutive { log_index: 52, expected: 51 })`) is indicating that is not the case. I've never seen this on Geth/OpenEthereum before, perhaps it's some sort of subtle difference between the implementations? Ofc, it could be a problem on our end too. Is there anything that jumps to mind @tkstanczak? :)

**Comment by pawanjay176** [comment] 2020-05-28 05:46
Hey @MysticRyuujin, wasn't able to reproduces the issue.
I am running a archive synced Nethermind 1.8.40-1-8fdc72ff0-20200528/X64-Linux and don't get the error. As Paul mentioned, the logs indicate that the deposit logs received from the eth1 node are not in order. 
Can you send me the output of this JSON rpc command so I can compare with my output? I'm @pawan on the lighthouse discord channel. 
```sh
curl --location --request POST 'localhost:8545/' \
                               --header 'Content-Type: application/json' \
                               --data-raw '{
                               "jsonrpc":"2.0",
                               "method":"eth_getLogs",
                               "params":[{"address":"0x42cc0fceb02015f145105cf6f19f90e9bea76558","fromBlock":2760066,"toBlock":2772924,"topics":["0x649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5"]}],
                               "id":1
                               }'
```

**Comment by MysticRyuujin** [comment] 2020-05-28 14:12
Here is the output of that curl command:
[output.txt](https://github.com/sigp/lighthouse/files/4696048/output.txt)

As for version, yesterday I installed it using the instructions here:
https://lighthouse-book.sigmaprime.io/installation.html

```
git clone https://github.com/sigp/lighthouse.git
cd lighthouse
make
```

```
lighthouse@eth2test:~/lighthouse$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by MysticRyuujin** [comment] 2020-05-28 14:31
FYI, I have 3 validators and they're all working...idk what the significance of this log is in relation to that.

https://witti.beaconcha.in/dashboard?validators=448,451,464

**Comment by protolambda** [comment] 2020-05-28 20:40
This may help, a debug log of all Witti deposit logs, datas, validators, etc.: https://gist.github.com/protolambda/34a44e23720ee6666e551d64e6a1dddc

**Comment by pawanjay176** [comment] 2020-05-28 21:20
So it looks like the nethermind node for some reason didn't process a deposit log. 

[This](https://gist.github.com/pawanjay176/780fd3d801c5df1d27def6cdc4aa2038) is a comparison of the deposits on the witti deposit contract fetched from an infura geth node vs the potentially buggy nethermind node generated using proto's [tool](https://github.com/protolambda/eth2-deposit-watch) . 

The nethermind node did not return valid deposit log `#51` on the witti deposit contract which caused the error.

To be clear, I synced a nethermind node locally (both fast mode and archive mode) and got the correct logs. I was only able to reproduce this by querying @MysticRyuujin 's nethermind node.

**Comment by MysticRyuujin** [comment] 2020-05-28 21:24
I did a fresh fast sync and the error went away. This could be another case of data corruption on my end. :-1: sorry everyone.

**Comment by pawanjay176** [comment] 2020-05-31 18:41
This is a bug in Nethermind and is being fixed in https://github.com/NethermindEth/nethermind/issues/1980

**Comment by pawanjay176** [comment] 2020-06-01 17:34
This has been fixed in Nethermind and will be in their next release :tada:

**Closed by pawanjay176** 2020-06-01 17:34 UTC

**Comment by NessDan** [comment] 2020-12-25 14:53
Hi, I'm having this same problem.

Fresh installation of `lighthouse v1.0.5 Baby Legs`. My `geth v1.9.25-stable-e7872729` is fully synced, and turning on the beacon node with this command: `lighthouse bn --staking --eth1-endpoints "http://127.0.0.1:8545,http://127.0.0.1:8546" --graffiti "<a href='keyboard.gg'>⌨⌨</a>" --freezer-dir "/ext-hdd/freezer" --port "9001" --target-peers "75"`

```
ERRO Failed to update eth1 cache error: Failed to update eth1 cache: "FailedToInsertDeposit(NonConsecutive { log_index: 5821, expected: 5016 })", retry_millis: 7000, service: eth1_rpc
ERRO Failed to update eth1 cache error: Failed to update eth1 cache: "FailedToInsertDeposit(NonConsecutive { log_index: 5821, expected: 5016 })", retry_millis: 7000, service: eth1_rpc
INFO Syncing est_time: 4 hrs 53 mins, speed: 8.00 slots/sec, distance: 141119 slots (2 weeks 5 days), peers: 78, service: slot_notifier
WARN Syncing eth1 block cache est_blocks_remaining: initializing deposits, msg: sync can take longer when using remote eth1 nodes, service: slot_notifier
```

It seems like the beacon node is working fine, but the error will continually log out.

**Comment by pawanjay176** [comment] 2020-12-26 14:32
@NessDan your geth node could be corrupted. Can you run the script here
https://github.com/pawanjay176/deposits-checker/blob/master/main.py

```
python3 main.py http://localhost:8545 <TRUSTED-INFURA-ENDPOINT>
```

If your geth node is fine, it should print out `All calls match` in the end.

**Comment by NessDan** [comment] 2020-12-26 20:51
@pawanjay176 thanks for the script, it was making progress but suddenly:

```
Checking in range 11313524 11314524
Checking in range 11314524 11315524
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main(sys.argv[1], sys.argv[2])
  File "main.py", line 51, in main
    to_check = get_deposit_logs_count(to_check_endpoint, r[0], r[1])
  File "main.py", line 40, in get_deposit_logs_count
    resp = send_rpc_request(endpoint, "eth_getLogs", params)
  File "main.py", line 21, in send_rpc_request
    resp = requests.post(endpoint, data = json.dumps(body), headers = HEADERS, timeout = TIMEOUT)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by pawanjay176** [comment] 2020-12-28 06:53
@NessDan looks like there's some issue with your local node as it suddenly closed connection. You can ping me on the sigp discord (@pawan) and I can try to help you out.

**Comment by NessDan** [comment] 2020-12-28 07:04
Update for anyone who finds this thread: Since this was a fresh installation of lighthouse (no validators imported or anything important) I was able to delete the `~/.lighthouse` directory along with my freezer folder and it synced up perfectly.

Seems like the issue was me launching Lighthouse before my eth 1 node had synced.
