### ISSUE TITLE
Incorrect phase0 block rewards in rewards API

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4929] opened 2023-11-16 14:27 UTC
## Description

The rewards calculated by the rewards API for phase0 blocks have the potential to be wrong in the presence of _attestations from slashed validators_. The reason for this is that the phase0 calculation reuses the op pool's code for attestation rewards, which ignores slashings as an optimisation:

https://github.com/sigp/lighthouse/blob/441fc1691b69f9edc4bbdc6665f3efab16265c9b/beacon_node/beacon_chain/src/beacon_block_reward.rs#L164-L171

https://github.com/sigp/lighthouse/blob/441fc1691b69f9edc4bbdc6665f3efab16265c9b/beacon_node/operation_pool/src/attestation.rs#L149-L152

Altair and later blocks are not affected.

## Version

Lighthouse v4.5.0

## Detail

- Validator x is slashed
- Validator x attests in epoch N with one set of flags (e.g. target + source)
- Validator x attests a second time in epoch N with a different set of flags (e.g. head + target + source)
- Validator y includes both attestations from validator x in a block

## Current Behaviour

The current API will reward the proposer (validator y) based on the flags of the attestation that was included in the block first (i.e. head + target).

## Expected Behaviour

The API should reward the proposer based on the flags of the _best_ attestation included for validator x. This is what the spec describes in `process_attestation` (for phase0).

**Comment by dknopik** [comment] 2024-01-18 18:25
Regarding the expected behaviour: In the phase0 spec, the proposer is rewarded at epoch boundaries in `get_inclusion_delay_deltas`. There, slashed attesters are skipped as we iterate over the return values of `get_unslashed_attesting_indices`. Therefore, shouldn't the expected behaviour be something like "The API should not reward for the attestations of validator x if validator x is slashed at the adequate epoch boundary, and otherwise rewards for both attestations."? 

Also, I am unsure about the notion of flags in this issue, since as far as I understand, that concept was introduced in Altair?

**Comment by michaelsproul** [comment] 2024-01-20 10:59
> "The API should not reward for the attestations of validator x if validator x is slashed at the adequate epoch boundary, and otherwise rewards for both attestations."?

Yeah this sounds right

> Also, I am unsure about the notion of flags in this issue, since as far as I understand, that concept was introduced in Altair?

You're right, I was a bit sloppy in my description there. In phase0 there's still a concept of matching head/target/source, which is what I meant. i.e. we should test 2 slashable attestations, one which matches e.g. source & target but not head, and one which matches all three. We should get the rewards for the latter, _even if_ the former is included in the block first.

**Comment by jimmygchen** [comment] 2024-10-03 13:19
Fixed in #5101 🎉

**Closed as completed by jimmygchen** 2024-10-03 13:19 UTC
Labels: bug, HTTP-API, rewards-api
