### ISSUE TITLE
Remove deficit gossipsub scoring during topic transition

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#3237] opened 2022-06-03 02:16 UTC
## Description

When we fork, we transition between gossipsub topics. We remain subscribed to old topics to keep track of any stragglers. As the optimal case involves everyone shifting to new topics, we would expect little to no messages being sent along the old topics.

This poses an issue for gossipsub scoring which expects a minimum number of messages to be sent on a given topic. Thus peers that left on the mesh on old topics get penalized for not sending us the expected minimum number of messages. This can result in disconnecting and potentially banning of honest peers.

In the event of a fork or topic transition, we should adjust the scoring parameters such that we eliminate the minimum deficit value indicating that it is perfectly fine to receive no messages on that topic. We can use this function: https://github.com/libp2p/rust-libp2p/blob/master/protocols/gossipsub/src/behaviour.rs#L900 to achieve this.

The `network` crate mainly controls the fork-switching logic, so it may need to inform the behaviour of when to adjust the scoring for topics.

**Comment by ackintosh** [comment] 2023-07-02 05:15
> We can use this function: https://github.com/libp2p/rust-libp2p/blob/master/protocols/gossipsub/src/behaviour.rs#L900 to achieve this.

@AgeManning Now the link might be pointing to a different place than you intended at the time. Is `set_application_score` the function?
https://github.com/libp2p/rust-libp2p/blob/master/protocols/gossipsub/src/behaviour.rs#L935

**Comment by divagant-martian** [comment] 2023-07-02 21:30
This is the one you want [`set_topic_params`](https://github.com/libp2p/rust-libp2p/blame/68e6bf9c3cd0d3317415a5ba31a62e91cba0a5d2/protocols/gossipsub/src/behaviour.rs#L920)

**Comment by ackintosh** [comment] 2023-07-04 22:39
@AgeManning @divagant-martian I was thinking about how to reproduce this issue locally, but I couldn't come up with anything. If you have any ideas, please let me know. 🙏

**Comment by divagant-martian** [comment] 2023-07-04 23:04
@ackintosh what did you try? I think reproducing this would be involved. 

Either a local testnet setup that makes it across a fork and monitoring metrics, or maybe a unitest - also somewhat involved (f you want to go this route [this file](https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/beacon_node/network/src/service/tests.rs) should give you a head start. 

In reality, I think these changes should be rather simple to tackle. The logic you need lives here: 
- [`next_fork_update`](https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/beacon_node/network/src/service.rs#L198-L202) triggered when a fork happens. Linked other two fields to note that subscription and unsubscription don't happen at the time of the fork. Subscription happens before, unsubscription after (as noted in this issue)
- [`update_next_fork`](https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/beacon_node/network/src/service.rs#L893) what is executed when a fork happens (so when the one above triggers) so here is where the changes would be done
- Since this is highly related to how unsubscriptions work: 
  - [This is what happens when we unsubscribe](https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/beacon_node/network/src/service.rs#L449-L454)
  - And here is where the unsubscriptions [are determined](https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/beacon_node/lighthouse_network/src/service/mod.rs#L572-L581)

The idea would be then to do something similar to what happens with unsubscriptions, removing the topic weight, but ofc, when the fork happens and not when unsubscriptions happen.

Let me know if this helps or you need more info

**Comment by ackintosh** [comment] 2023-07-08 05:41
Thanks for the detailed explanation. it was really helpful!

I have read the code around the links you provided. Below is a diagram of my understanding:



![Image](https://github.com/sigp/lighthouse/assets/1885716/155e8b7f-f7a2-4e4d-9151-db88ae174785)

**Comment by divagant-martian** [comment] 2023-07-08 13:40
yeah I think that's correct

**Comment by ackintosh** [comment] 2023-07-22 20:26
Filed a draft PR  https://github.com/sigp/lighthouse/pull/4486 to address this issue, and tackling the unit testing.

Quoting from the changes of unit test:
https://github.com/sigp/lighthouse/blob/5589e875be0644fec13b083050cb3b3aff4ab0bf/beacon_node/network/src/service/tests.rs#L199-L216

I also filed a PR to libp2p to add a getter function obtaining `TopicScoreParam` since there is no way to test topic_weight.
https://github.com/libp2p/rust-libp2p/pull/4231

**Comment by ackintosh** [comment] 2023-08-02 23:55
Now this issue is blocked by https://github.com/libp2p/rust-libp2p/pull/4231. Will resume once the PR in rust-libp2p has been merged and released.

**Comment by ackintosh** [comment] 2023-08-26 23:01
Note for self: libp2p will be updated to the latest version (0.52.3) in https://github.com/sigp/lighthouse/pull/4639. The version includes the getter function that is needed to progress this issue.

**Comment by AgeManning** [comment] 2023-09-26 00:53
It has been merged, can you ping me when this one is ready too

**Comment by ackintosh** [comment] 2023-09-30 05:40
@AgeManning https://github.com/sigp/lighthouse/pull/4486 is ready to merge. 🙂

**Comment by divagant-martian** [comment] 2023-10-06 04:25
closed by #4486

**Closed as completed by divagant-martian** 2023-10-06 04:25 UTC
Labels: ready-for-merge, Networking
