### ISSUE TITLE
Fail to make on Raspian 10 -

### ISSUE THREAD

**Issue by adv0r** [sigp/lighthouse#1585] opened 2020-09-04 22:57 UTC
## Description

Trying to install with make on a raspberry pi 4 model b.  Fails quickly compiling blst.
Maybe some clues here -> https://github.com/prysmaticlabs/prysm/issues/5310 

## Version
Lighthouse v0.2.8

```
pi@pistake:~/lighthouse $ cargo --version --verbose
cargo 1.46.0 (149022b1d 2020-07-17)
release: 1.46.0
commit-hash: 149022b1d8f382e69c1616f6a46b69ebf59e2dea
commit-date: 2020-07-17
```
## Present Behaviour
cannot compile blst

```
Compiling blst v0.1.1 (https://github.com/sigp/blst.git?rev=284f7059642851c760a09fb1708bcb59c7ca323c#284f7059)
error[E0425]: cannot find function `assembly` in this scope
  --> /home/pi/.cargo/git/checkouts/blst-4627ab328529f030/284f705/bindings/rust/build.rs:63:5
   |
63 |     assembly(&mut file_vec, &build_dir);
   |     ^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `blst`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lighthouse v0.2.8 (/home/pi/lighthouse/lighthouse)`, intermediate artifacts can be found at `/home/pi/lighthouse/target`

Caused by:
  build failed
make: *** [Makefile:20: install] Error 101
```

## Expected Behaviour

installing correctly 

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment] 2020-09-05 02:16
Closing as a duplicate of #706. We still have no plans to support 32-bit OSes, for the reasons highlighted in the other issue

**Closed by michaelsproul** 2020-09-05 02:16 UTC
