### ISSUE TITLE
Capella proposer preparation clones a beacon state

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3998] opened 2023-02-17 07:34 UTC
## Description

In `BeaconChain::prepare_beacon_proposer`, we're always cloning the state in order to compute the list of withdrawals: 

https://github.com/sigp/lighthouse/blob/9a41f65b892e4c679d353ddc00e87bd93b521026/beacon_node/beacon_chain/src/beacon_chain.rs#L4764-L4773

It's nice to avoid state clones since they're generally slow (10s of millis) and use a bunch of RAM (100s of MBs). I think there's at least one case were we can avoid the the state clone; when producing a block in the same epoch as its parent. Hopefully there's some more cases too.

We could also look at some sort of caching here to avoid repeat calls to the same method.

I think this behavior is OK for Sepolia, however I think we should optimise it before mainnet.

**Comment by michaelsproul** [comment] 2023-02-17 10:05
Duplicate of #3896 which has some more info

**Comment by michaelsproul** [comment] 2023-02-20 00:45
I'm gonna tackle this (and #3896 by implication)

**Closed as completed** 2023-03-07 22:09 UTC
Labels: capella
