### ISSUE TITLE
Lighthouse Beacon node OOM

### ISSUE THREAD

**Issue by wouterdegeus** [sigp/lighthouse#2220] opened 2021-02-22 10:04 UTC
## Description

After I got a notice regarding my Validator missing an attestation I went through the logs to find it unable to connect to the Beacon Node.
Checking the Beacon Node it became clear that it got stuck in some sort of loop, which after a while triggered the OOM killer (freeing up to 15GB of memory from what I see in Grafana).

The logs show this:
```
Feb 22 09:31:59.333 INFO New block received                      hash: 0xde48…2035, slot: 596558
Feb 22 09:32:05.001 INFO Synced                                  slot: 596558, block: 0xde48…2035, epoch: 18642, finalized_epoch: 18640, finalized_root: 0x72f6…ecbe, peers: 49, service: slot_notifier
Feb 22 09:32:11.491 INFO New block received                      hash: 0x6418…0ed6, slot: 596559
Feb 22 09:32:17.000 INFO Synced                                  slot: 596559, block: 0x6418…0ed6, epoch: 18642, finalized_epoch: 18640, finalized_root: 0x72f6…ecbe, peers: 49, service: slot_notifier
Feb 22 09:32:23.623 INFO New block received                      hash: 0xa74b…5c55, slot: 596560
Feb 22 09:32:29.001 INFO Synced                                  slot: 596560, block: 0xa74b…5c55, epoch: 18642, finalized_epoch: 18640, finalized_root: 0x72f6…ecbe, peers: 48, service: slot_notifier
Feb 22 09:32:34.181 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.239 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.295 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.334 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.335 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.338 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.339 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.340 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.341 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.350 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.353 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.358 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.363 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.365 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.366 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.368 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.395 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.397 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.397 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.398 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.399 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.401 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.401 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.401 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.402 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.404 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.405 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:34.406 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
< keeps repeating a lot >
Feb 22 09:32:41.000 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
Feb 22 09:32:41.000 INFO Synced                                  slot: 596561, block: 0x6775…c702, epoch: 18642, finalized_epoch: 18640, finalized_root: 0x72f6…ecbe, peers: 51, service: slot_notifier
Feb 22 09:32:41.001 INFO Address updated                         udp_port: 11363, ip: ::ffff:<censored>, service: libp2p
< keeps repeating a lot >
```
Until OOM finally kills it.
A quick count:
```bash
$ grep "Feb 22 09:" lighthouse-bn-log | grep "INFO Address updated                         udp_port: 11363" | wc -l
37282
```
Next it restarts automatically through docker at Feb 22 09:33:45.132, after which it seems to work fine up until Feb 22 10:07:53.001 where it gets stuck in this loop again. (this time on port 9000)
Eventually it seems to get out of this loop however:
```
Feb 22 10:10:04.336 INFO Address updated                         udp_port: 9000, ip: ::ffff:<myip>, service: libp2p
Feb 22 10:10:04.336 INFO Address updated                         udp_port: 9000, ip: ::ffff:<myip>, service: libp2p
Feb 22 10:10:04.338 INFO Address updated                         udp_port: 9000, ip: ::ffff:<myip>, service: libp2p
Feb 22 10:10:04.340 INFO Address updated                         udp_port: 9000, ip: ::ffff:<myip>, service: libp2p
Feb 22 10:10:04.341 INFO Address updated                         udp_port: 59079, ip: <myip>, service: libp2p
Feb 22 10:10:05.001 INFO Synced                                  slot: 596748, block: 0x26af…6cc3, epoch: 18648, finalized_epoch: 18646, finalized_root: 0x43c1…28e1, peers: 49, service: slot_notifier
```

Not sure exactly what's going on there, one thing that is interesting is that the time it gets out it doesn't seem to use IPv6 notation, so maybe this is IPv6 related?
Digging through the logs a bit more it seems like this happens more often, usually only a few notices of the IPv6 variant after which it "sees" the proper IPv4 address again.

## Version

Lighthouse v1.1.1
Rust v1.50
Built on docker

## Present Behaviour

Gets stuck in address update loop with IPv6 address notation until it either OOMs or sees the IPv4 variant of the same address.

## Expected Behaviour

Stick to the proper address, it doesn't really ever change.

## Steps to resolve

Unknown.

**Comment by michaelsproul** [comment] 2021-02-22 11:08
Hi @wouterdegeus! Thanks for the detailed bug report. This is a known issue that was fixed in v1.1.3 released just a few hours ago. Please try that release and let us know if your problems persist!

Closing as a duplicate of https://github.com/sigp/lighthouse/issues/2215, will re-open as necessary

**Closed as completed by michaelsproul** 2021-02-22 11:08 UTC
