### ISSUE TITLE
BlockDownloadFailed (TimedOut) error downloading Eth1 blocks [Infura, Alchemy, local Geth]

### ISSUE THREAD

**Issue by onyxrev** [sigp/lighthouse#2372] opened 2021-05-27 19:44 UTC
## Description

My validator has been running on `mainnet` for a few days now. I'm syncing a local Geth client in the background for the long haul, but for now my Beacon node has been hooked up to Infura. I successfully made deposits and my validators are active and attesting, so the ETH1 endpoint was working at some point. But in the past day I've been seeing the following...

`May 27 16:22:00 ethereum lighthouse[165241]: May 27 16:22:00.198 ERRO Failed to update eth1 cache             error: Failed to update Eth1 service: "All fallback errored: https://mainnet.infura.io/v3/xxx => BlockDownloadFailed(\"Request failed: reqwest::Error { kind: Request, url: Url { scheme: \\\"https\\\", username: \\\"\\\", password: None, host: Some(Domain(\\\"mainnet.infura.io\\\")), port: None, path: \\\"/v3/xxx\\\", query: None, fragment: None }, source: TimedOut }\")", retry_millis: 7000, service: eth1_rpc`

I thought that maybe Infura was rate-limiting me, but when I log into Infura I see in their dashboard that I'm both well below the limit and also that the node appears to be successfully making requests.

I signed up for Alchemy to try another provider and I'm seeing the same behavior. Requests are made, Alchemy's dashboard shows the requests are happening and responding in the 10ms range.

Then I hooked up Lighthouse to the local Geth (even though it's not done syncing), and saw the same `TimedOut` behavior even on localhost, which seems unlikely.

I can `curl` Infura and Alchemy and Geth just fine. Infura responds to `POST` with JSON. Curl doesn't time out. This leads me to believe that there is some sort of issue with the Rust client itself.

## Version

```
Lighthouse v1.3.0-3a24ca5
BLS Library: blst-modern
Specs: mainnet (true), minimal (false), v0.12.3 (false)
```

Local Geth is

```
1.10.3-stable-991384a7
```

Local Geth sync progress is currently:

```
{
  currentBlock: 12518158,
  highestBlock: 12518277,
  knownStates: 732082090,
  pulledStates: 731954144,
  startingBlock: 12514158
}
```

I have no idea what the remote nodes are for Infura or Alchemy.

## Present Behaviour

Eth1 syncing is timing out with multiple providers, even when response times seem reasonable. Connections appear to be initiating but not resolving in the rust client.

## Expected Behaviour

Eth1 endpoints should be queried. Replies should be parsed and cached.

## Steps to resolve

Unknown.

**Comment by onyxrev** [comment] 2021-05-28 00:27
I have a suspicion this has to do with EIP-155.

Geth logs:

`May 28 00:23:55 ethereum geth[802]: WARN [05-28|00:23:55.646] Served eth_chainId                       conn=127.0.0.1:41696 reqid=1 t="24.664µs"  err="chain not synced beyond EIP-155 replay-protection fork block"`

There's a flag to enable the old behavior in Geth...

`--rpc.allow-unprotected-txs`

**Comment by paulhauner** [comment] 2021-05-30 00:29
Hmm, interesting. We haven't seen anything like this before AFAIK so it'll be interesting to see the cause.

Are you running inside a docker container or using any sort of firewall setup?

> I successfully made deposits and my validators are active and attesting, so the ETH1 endpoint was working at some point.

FYI you can attest without an Eth1 connection, so this is not strictly the case. Sometimes you might have issues producing blocks without Eth1, though. It'll always generate `ERRO` logs if it can't update the Eth1 cache, the lack of these would indicate a successful connection.

**Comment by onyxrev** [comment] 2021-05-30 01:07
This is running directly on a Zotac mini PC (i5, 32GB RAM, 2TB SSD) running Ubuntu Focal. There is no firewall on the local machine. It’s running behind a UniFi Security Gateway with a firewall, pertinent ports forwarded through NAT, and uPnP turned on. ISP is Verizon FiOS.

**Comment by onyxrev** [comment] 2021-05-30 01:15
> FYI you can attest without an Eth1 connection, so this is not strictly the case.

Yes, but would the validator deposit have been registered with the beacon node without an Eth1 connection?

**Comment by paulhauner** [comment] 2021-05-30 09:03
> Yes, but would the validator deposit have been registered with the beacon node without an Eth1 connection?

Yep, the deposits are included in blocks by other validators. An Eth1 node is only required for *producing* blocks (specifically, producing those blocks where new deposits are to be included).

**Comment by paulhauner** [comment] 2021-05-30 09:07
> This is running directly on a Zotac mini PC (i5, 32GB RAM, 2TB SSD) running Ubuntu Focal. There is no firewall on the local machine. It’s running behind a UniFi Security Gateway with a firewall, pertinent ports forwarded through NAT, and uPnP turned on. ISP is Verizon FiOS.

Thanks for the details. Is it running in a `systemd` service, or straight from the shell of the user that's able to `curl` successfully?

**Comment by onyxrev** [comment] 2021-05-30 19:06
> Thanks for the details. Is it running in a systemd service, or straight from the shell of the user that's able to curl successfully?

Yup, `systemd`. This is the service definition:

```
[Unit]
Description=Lighthouse Eth2 Client Beacon Node
Wants=network-online.target
After=network-online.target

[Service]
User=lighthousebeacon
Group=lighthousebeacon
Type=simple
Restart=always
RestartSec=5
ExecStart=/usr/local/bin/lighthouse bn --network mainnet --datadir /var/lib/lighthouse --staking --eth1-endpoints http://127.0.0.1:8545,https://mainnet.infura.io/v3/xxx

[Install]
WantedBy=multi-user.target
```

I followed [this guide](https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-lighthouse-41de20513b12) to set up the validator (although I skipped the metrics and UFW stuff).

If I give the `lighthousebeacon` user a shell, I can curl the endpoints as the user, but the errors persist in the Lighthouse logs.

```
$ sudo usermod --shell /bin/bash lighthousebeacon
lighthousebeacon@ethereum:~$ curl https://mainnet.infura.io/v3/xxx -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params": [],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0xbf4e78"}

lighthousebeacon@ethereum:/home/dan$ curl http://localhost:8545 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params": [],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x0"}
```

**Comment by AgeManning** [comment] 2021-05-31 02:08
Do you have any local firewall rules?
Have you tried disabling all firewalls temporarily and does lighthouse still timeout with geth on localhost?

**Comment by paulhauner** [comment] 2021-05-31 04:12
> If I give the lighthousebeacon user a shell, I can curl the endpoints as the user, but the errors persist in the Lighthouse logs.

Thanks for trying this. I'm a bit stumped here, but another option is trying to run the `ExecStart` command from your typical user account and shell.

Also, I noticed the logs in your original post don't contain a failure to reach `localhost:8545`. If you try the above, could you please include the logs with a localhost failure?

**Comment by onyxrev** [comment] 2021-05-31 20:27
I still see the same behavior when running the `ExecStart` command as my privileged user.

Logs:

`
May 31 20:13:27 ethereum lighthouse[53290]: May 31 20:13:27.894 WARN Error connecting to eth1 node endpoint  action: trying fallbacks, endpoint: https://mainnet.infura.io/v3/xxx, service: eth1_rpc
May 31 20:13:27 ethereum lighthouse[53290]: May 31 20:13:27.894 CRIT Couldn't connect to any eth1 node. Please ensure that you have an eth1 http server running locally on http://localhost:8545 or specify one or more (remote) endpoints using `--eth1-endpoints <COMMA-SEPARATED-SERVER-ADDRESSES>`. Also ensure that `eth` and `net` apis are enabled on the eth1 http server, warning: BLOCK PROPOSALS WILL FAIL WITHOUT VALID, SYNCED ETH1 CONNECTION, service: eth1_rpc
May 31 20:13:27 ethereum lighthouse[53290]: May 31 20:13:27.894 ERRO Failed to update eth1 cache             error: Failed to update Eth1 service: "All fallback errored: http://127.0.0.1:8545 => EndpointError(NotReachable), https://mainnet.infura.io/v3/xxx => EndpointError(NotReachable)", retry_millis: 7000, service: eth1_rpc
May 31 20:13:27 ethereum lighthouse[53290]: May 31 20:13:27.944 WARN Error connecting to eth1 node endpoint  action: trying fallbacks, endpoint: http://127.0.0.1:8545, service: eth1_rpc
May 31 20:13:28 ethereum lighthouse[53290]: May 31 20:13:28.249 WARN Error connecting to eth1 node endpoint  action: trying fallbacks, endpoint: http://127.0.0.1:8545, service: eth1_rpc
`

> Do you have any local firewall rules?

There's no firewall active on this machine.

```
dan@ethereum:~$ sudo ufw status
Status: inactive

dan@ethereum:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

Only other thing I can think of is to try Lighthouse again once my local Geth is fully synced. I'm stumped too!

**Comment by onyxrev** [comment] 2021-05-31 21:46
I set up Prysm on the same box using the same user and a systemd definition...

`
May 31 21:45:48 ethereum prysm.sh[56326]: time="2021-05-31 21:45:48" level=info msg="Connected to eth1 proof-of-work chain" endpoint="https://eth-mainnet.alchemyapi.io/***" prefix=powchain
`

Prysm can connect to any of the Eth1 endpoints.

**Comment by paulhauner** [comment] 2021-06-01 00:14
Thanks again for detailed troubleshooting steps. I made some progress whilst doing some local testing:

### Scenario 1: Python websever

I ran a local, function-less Python server on 8545:

```
python -m http.server 8545
```

Then, I started Lighthouse with:

```
lighthouse bn --debug-level info --staking --eth1-endpoints http://127.0.0.1:8545
```

I get the following errors from Lighthouse:

```
ERRO Failed to update eth1 cache             error: Failed to update Eth1 service: "All fallback errored: http://127.0.0.1:8545/ => EndpointError(NotReachable)", retry_millis: 60000, service: eth1_rpc
```

For each request, the Python webserver shows:

```
127.0.0.1 - - [01/Jun/2021 09:51:18] code 501, message Unsupported method ('POST')
127.0.0.1 - - [01/Jun/2021 09:51:18] "POST / HTTP/1.1" 501 -
```

And `tcpdump` shows:

```
sudo tcpdump -i lo port 8545
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on lo, link-type EN10MB (Ethernet), snapshot length 262144 bytes

09:54:18.068793 IP localhost.49536 > localhost.8545: Flags [S], seq 1245988730, win 65495, options [mss 65495,sackOK,TS val 837643767 ecr 0,nop,wscale 7], length 0
09:54:18.068807 IP localhost.8545 > localhost.49536: Flags [S.], seq 482249808, ack 1245988731, win 65483, options [mss 65495,sackOK,TS val 837643767 ecr 837643767,nop,wscale 7], length 0
09:54:18.068820 IP localhost.49536 > localhost.8545: Flags [.], ack 1, win 512, options [nop,nop,TS val 837643767 ecr 837643767], length 0
09:54:18.068993 IP localhost.49536 > localhost.8545: Flags [P.], seq 1:166, ack 1, win 512, options [nop,nop,TS val 837643767 ecr 837643767], length 165
09:54:18.069005 IP localhost.8545 > localhost.49536: Flags [.], ack 166, win 511, options [nop,nop,TS val 837643767 ecr 837643767], length 0
09:54:18.069530 IP localhost.8545 > localhost.49536: Flags [P.], seq 1:198, ack 166, win 512, options [nop,nop,TS val 837643768 ecr 837643767], length 197
09:54:18.069542 IP localhost.49536 > localhost.8545: Flags [.], ack 198, win 511, options [nop,nop,TS val 837643768 ecr 837643768], length 0
09:54:18.069562 IP localhost.8545 > localhost.49536: Flags [P.], seq 198:695, ack 166, win 512, options [nop,nop,TS val 837643768 ecr 837643768], length 497
09:54:18.069567 IP localhost.49536 > localhost.8545: Flags [.], ack 695, win 508, options [nop,nop,TS val 837643768 ecr 837643768], length 0
09:54:18.069597 IP localhost.8545 > localhost.49536: Flags [F.], seq 695, ack 166, win 512, options [nop,nop,TS val 837643768 ecr 837643768], length 0
09:54:18.069611 IP localhost.49536 > localhost.8545: Flags [F.], seq 166, ack 695, win 508, options [nop,nop,TS val 837643768 ecr 837643768], length 0
09:54:18.069622 IP localhost.8545 > localhost.49536: Flags [.], ack 167, win 512, options [nop,nop,TS val 837643768 ecr 837643768], length 0
09:54:18.069634 IP localhost.49536 > localhost.8545: Flags [.], ack 696, win 508, options [nop,nop,TS val 837643768 ecr 837643768], length 0
```

### Scenario 2: No webserver

I *do not* run the Python webserver (nothing is listening on 8545), but stilll start Lighthouse with:

```
lighthouse bn --debug-level info --staking --eth1-endpoints http://127.0.0.1:8545
```

Lighthouse returns the *same error* (:grimacing:):

```
ERRO Failed to update eth1 cache             error: Failed to update Eth1 service: "All fallback errored: http://127.0.0.1:8545/ => EndpointError(NotReachable)", retry_millis: 60000, service: eth1_rpc
```

And `tcpdump` now shows:

```
sudo tcpdump -i lo port 8545
[sudo] password for paul:
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on lo, link-type EN10MB (Ethernet), snapshot length 262144 bytes
10:02:52.343353 IP localhost.49544 > localhost.8545: Flags [S], seq 3571073100, win 65495, options [mss 65495,sackOK,TS val 838158042 ecr 0,nop,wscale 7], length 0
10:02:52.343361 IP localhost.8545 > localhost.49544: Flags [R.], seq 0, ack 3571073101, win 0, length 0
```

### Scenario 3: Bad Infura Key

I tried running Lighthouse against a bad Infura URL (append `_JUNK` to the secret) with:

```
lighthouse bn --debug-level debug --staking --eth1-endpoints https://mainnet.infura.io/v3/<SECRET>_JUNK
```

Behold, I also get *the same error* (:grimacing: :grimacing:) :

```
ERRO Failed to update eth1 cache             error: Failed to update Eth1 service: "All fallback errored: https://mainnet.infura.io/ => EndpointError(NotReachable)", retry_millis: 60000, service: eth1_rpc
```

### Summary

From this line of investigation I think we've learned two things:

1. Lighthouse seems to be returning `NotReachable` for different types of errors (500, 403(?) and legitimately not reachable). This is Bad Behaviour which makes debugging harder. Apologies for this, I wasn't aware. I'll look into it.
2. We can use `tcpdump` to see if Lighthouse is at least *trying* to make outgoing calls and then use the amount of traffic to infer if it's actually hitting a server or some sort. 

So, from here I'd be tempted to double check your Infura keys and perhaps try quoting them to ensure they're not getting mangled by the shell. Perhaps trying `tcpdump` will be interesting, up to you. In the meantime I will try and make Lighthouse return better errors!

**Comment by paulhauner** [comment] 2021-06-01 00:55
I made some progress with returning more detailed errors :tada: https://github.com/sigp/lighthouse/pull/2383 includes much more detail with these errors (see the PR description for examples that relate to my previous comment in this thread).

So, for you @onyxrev there are two options:

1. Wait for the next release which contains these fixes (we're preparing a new release scheduled for later this week, but we're still testing some extensive changes to the networking stack).
1. Build https://github.com/sigp/lighthouse/pull/2383, use the detailed error messages to determine what the issue is and then swap back to `stable` (i.e., the [latest release](https://github.com/sigp/lighthouse/releases/tag/v1.3.0)) when your issues are straightened out.

I do not recommend running https://github.com/sigp/lighthouse/pull/2383 (which builds upon our `unstable` branch) for anything beyond intial testing at the moment. We're still working on some known bugs in `unstable` which are not present on `stable`.

Thanks for the time you've spent so far troubleshooting with us :pray:

**Comment by onyxrev** [comment] 2021-06-01 18:17
Thanks for making those improvements. 

I've switched over to Prysm for now on my production validator, but am still running the Lighthouse beacon node alongside. I'll try the next stable release to see what's different. I did verify that Lighthouse was making requests to the Eth1 endpoints, for what it's worth.

**Comment by paulhauner** [comment] 2021-06-04 05:29
> I'll try the next stable release to see what's different. I did verify that Lighthouse was making requests to the Eth1 endpoints, for what it's worth.

Thanks :pray:  We have a [release candidate](https://github.com/sigp/lighthouse/releases/tag/v1.4.0-rc.0) out now which includes those changes and are expecting to publish the full release next week.

**Comment by onyxrev** [comment] 2021-06-11 14:23
I upgraded to `1.4.0` and am not seeing the timeout errors anymore. I removed my local geth endpoint, leaving just Infura. And voilà... no errors anymore. So I guess the error handling in `1.3.0` was incorrectly logging failures. This makes sense because I could confirm that the requests were being made.

I've cut back over to lighthouse from prysm for my validators now. Thanks for making those changes! I'd be happy to have this bug closed, but I'll let you folks close it if you're satisfied.

**Comment by paulhauner** [comment] 2021-06-14 23:30
Oh glad to hear that has been fixed @onyxrev! Sorry for the inconvenience and I'm glad to hear you're back with Lighthouse :relaxed: 

It's a bit of a shame that we didn't manage to pinpoint the issue, but I think we're beyond the point of troubleshooting it now. If we do see it again, at least we have more detailed logs thanks to this issue. That should make it much easier to diagnose.

Thanks again for the detailed issue and assistance throughout!

**Closed as completed by paulhauner** 2021-06-14 23:30 UTC
Labels: bug
