### ISSUE TITLE
DB error when reading head state: SszDecodeError

### ISSUE THREAD

**Issue by newearthmartin** [sigp/lighthouse#2444] opened 2021-07-12 04:24 UTC
## Description

Lighthouse fails to start the beacon node because of problem reading DB head state.

## Version

v1.4.0-3b600ac

## Present Behaviour

Beacon node fails to start because a problem while reading the DB head state. In this case:  `SszDecodeError(OffsetOutOfBounds(4083498482))`. Lighthouse does not try to solve this automatically or present information on how to solve it manually.

```
Jul 11 23:07:58.905 INFO Starting beacon chain                   method: resume, service: beacon
Jul 11 23:08:10.774 INFO Block production enabled                method: json rpc via http, endpoints: ["http://127.0.0.1:8545/"]
Jul 11 23:08:11.267 CRIT Failed to start beacon node             reason: Failed to build beacon chain: DB error when reading head state: SszDecodeError(OffsetOutOfBounds(4083498482))
Jul 11 23:08:11.267 INFO Internal shutdown received              reason: Failed to start beacon node
Jul 11 23:08:11.267 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
```

## Expected Behaviour

The application should try to solve this automatically. If it is unsolvable and the DB should be purged, it should be clearly expressed. It should not leave the user in the dark as to wether they should delete all data and start over or not.

**Comment by paulhauner** [comment] 2021-07-12 04:30
Sorry to hear you're having issues. This is an uncommon error, it's typically the result of swapping between testnet/mainnet using the same data directory. It could also be caused by database corruption.

Try the `--purge-db` flag to start with a new database.

I'd be interested to know:

- If `--purge-db` solved your issue.
- If you were using mainnet or a testnet.
- If you already had a fully- or somewhat-synced node. Or, if this happened the first time you started.

**Comment by newearthmartin** [comment] 2021-07-12 04:40
Hi thanks for answering.

`--purge-db` solved it.

I was using pyrmont testnet but switched to mainnet, I'd swear that I changed the datadir but maybe I didn't 😀 
I was halfway through syncing.

**Comment by paulhauner** [comment] 2021-07-12 05:10
> --purge-db solved it.

Great to hear!

> I was using pyrmont testnet but switched to mainnet, I'd swear that I changed the datadir but maybe I didn't grinning

In that case, it sounds like this is not database corruption or an application error. I've created #2445 which returns more information when this case is encountered, this issue will be automatically closed when that merges :slightly_smiling_face:

**Comment by newearthmartin** [comment] 2021-07-12 05:20
Amazing! Glad to contribute

**Comment by paulhauner** [comment] 2021-07-29 05:42
Resolved by #2445

**Closed as completed by paulhauner** 2021-07-29 05:42 UTC
Labels: bug

**Comment by bonedaddy** [comment] 2023-05-26 04:52
Unfortunately just ran into this issue using lighthouse v4.2.0 trying to checkpoint sync of a nimbus client i'm running.

**Comment by paulhauner** [comment] 2023-05-26 04:56
> Unfortunately just ran into this issue using lighthouse v4.2.0 trying to checkpoint sync of a nimbus client i'm running.

A slightly different instance of the `OffsetOutOfBounds` error can be encountered when:

- Trying to checkpoint sync between nodes on two different networks (e.g., LH on Goerli, Nimbus on Mainnet)
- Trying to checkpoint sync from a post-fork client that's not configured for that fork (e.g., LH is pre-v4.0.0 and Nimbus has gone through the Capella fork).

So, I'd suggest checking that LH and Nimbus are on the same network. Also that LH and Nimbus are running recent versions.

**Comment by lourou** [comment] 2023-06-11 06:58
Same issue with lighthouse v4.2.0. I solved it by restarting the beacon node. Syncing properly with finalized chain now.
