### ISSUE TITLE
Investigate backfill sync slowness

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#4508] opened 2023-07-14 19:26 UTC
## Description

Backfill sync speeds on devnet 7 seem very slow. Seeing max speed of 8 slots/sec on my m1 macbook pro. 
We do expect sync speed to reduce since we only process after receiving both blocks and blobs, however this is atleast an order magnitude decrease in sync speeds which probably needs more investigation.

My initial guess after glancing at the logs, it seems like it is taking almost 30 secs for a single batch to get downloaded which isn't ideal.

This also might be a false alarm with my local setup, need more data points.

**Comment by realbigsean** [comment] 2024-01-18 21:09
whoops, duplicate of https://github.com/sigp/lighthouse/issues/5058

**Closed as completed by realbigsean** 2024-01-18 21:09 UTC
Labels: deneb
