### ISSUE TITLE
Don't downscore on `NoResponseReturned`

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#5695] opened 2024-05-02 19:11 UTC
## Description

Sample of logs where we query a peer for a block in a single lookup, don't get a response, downscore, then retry and the retry is successful: 

```
May 01 15:01:26.198 DEBG Received unknown parent blob message    parent_root: 0xadd6…28c6, block_root: 0x88dd…6470, service: sync
May 01 15:01:26.198 DEBG Searching for components of a block with unknown parent, block: 0x88ddccb915fb60496c9f950c8dccbccf2e22d75aa38139b8e5e7286f1dd66470, peer_ids: [PeerId("16Uiu2HAmFhXQfvmdC55dC9mjSENYrDUnSsjeZ4oxwWZSzqZAqiMA")], service: sync
May 01 15:01:26.198 DEBG Sending BlocksByRoot Request            id: SingleLookupReqId { lookup_id: 73528, req_id: 73529 }, peer: 16Uiu2HAmFhXQfvmdC55dC9mjSENYrDUnSsjeZ4oxwWZSzqZAqiMA, block_root: 0x88ddccb915fb60496c9f950c8dccbccf2e22d75aa38139b8e5e7286f1dd66470, method: BlocksByRoot, service: sync
May 01 15:01:26.217 DEBG Rejected gossip block                   slot: 1556107, graffiti: 🧱🔥 Kiln.fi 🔥🧱, error: ParentUnknown(parent_root:0xadd6…28c6), service: beacon
May 01 15:01:26.222 DEBG Unknown parent for gossip block         root: 0x88ddccb915fb60496c9f950c8dccbccf2e22d75aa38139b8e5e7286f1dd66470
May 01 15:01:26.222 DEBG Received unknown parent block message   parent_root: 0xadd6…28c6, block_root: 0x88dd…6470, service: sync
May 01 15:01:26.556 DEBG Sync reporting peer                     msg: NoResponseReturned, action: Low Tolerance Error, peer_id: 16Uiu2HAmFhXQfvmdC55dC9mjSENYrDUnSsjeZ4oxwWZSzqZAqiMA, service: sync
May 01 15:01:26.556 DEBG Received lookup download failure        error: Lookup Verify Error: NoResponseReturned, response_type: Block, peer_id: 16Uiu2HAmFhXQfvmdC55dC9mjSENYrDUnSsjeZ4oxwWZSzqZAqiMA, block_root: 0x88dd…6470, service: sync
May 01 15:01:26.556 DEBG Peer score adjusted                     score: -14.56, peer_id: 16Uiu2HAmFhXQfvmdC55dC9mjSENYrDUnSsjeZ4oxwWZSzqZAqiMA, msg: NoResponseReturned, service: libp2p
May 01 15:01:26.556 DEBG Sending BlocksByRoot Request            id: SingleLookupReqId { lookup_id: 73528, req_id: 73531 }, peer: 16Uiu2HAmFhXQfvmdC55dC9mjSENYrDUnSsjeZ4oxwWZSzqZAqiMA, block_root: 0x88ddccb915fb60496c9f950c8dccbccf2e22d75aa38139b8e5e7286f1dd66470, method: BlocksByRoot, service: sync
May 01 15:01:27.103 DEBG Received lookup download success        response_type: Block, peer_id: 16Uiu2HAmFhXQfvmdC55dC9mjSENYrDUnSsjeZ4oxwWZSzqZAqiMA, block_root: 0x88dd…6470, service: sync
```

A `NoResponseReturned` can happen if we get an unknown parent and request block/blobs for the current slot from a peer. This isn't malicious if they can't respond, and on retry we should be requesting a separate peer, not the same one.

**Comment by dapplion** [comment] 2024-05-03 08:20
Closing for 
- https://github.com/sigp/lighthouse/issues/5707

I think we should downscore peers that do not have blocks. The issue is that we are requesting peers for blocks when they might not have it

**Closed as completed by dapplion** 2024-05-03 08:20 UTC
