### ISSUE TITLE
InsufficientPeers resulting in missing sync commitees

### ISSUE THREAD

**Issue by fkbenjamin** [sigp/lighthouse#2858] opened 2021-12-07 13:34 UTC
## Description

Our lighthouse nodes occasionally start to miss attestations and today also missed sync committees. Looking at the beaconchain node logs, it seems that it has issues with publishing these messages because of  Insufficient Peers, despite being connected to 50+ peers. Restarting the node solves the issue.

## Version

Lighthouse v2.0.1 
(using vouch as the validator client)

## Present Behaviour

Describe the present behaviour of the application, with regards to this
issue.

```
Dec 07 13:30:41 lhs-val01 lighthouse[997]: Dec 07 13:30:41.000 INFO Synced                                  slot: 2671351, block: 0xb807…9b44, epoch: 83479, finalized_epoch: 83477, finalized_root: 0x0e20…8ae0, peers: 55, service: slot_notifier
Dec 07 13:30:49 lhs-val01 lighthouse[997]: Dec 07 13:30:49.652 INFO New block received                      hash: 0x81272318e6771c48a8cdd656255c1c61afd45d9a6cc5d037d28059235600e05e, slot: 2671352
Dec 07 13:30:50 lhs-val01 lighthouse[997]: Dec 07 13:30:50.467 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Dec 07 13:30:51 lhs-val01 lighthouse[997]: Dec 07 13:30:51.487 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Dec 07 13:30:51 lhs-val01 lighthouse[997]: Dec 07 13:30:51.490 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Dec 07 13:30:51 lhs-val01 lighthouse[997]: Dec 07 13:30:51.491 WARN Could not publish message               error: InsufficientPeers, service: libp2p
```

## Steps to resolve

Restarting the beaconchain node usually resolves the issue.

**Comment by paulhauner** [comment] 2021-12-14 01:01
Thanks for reporting @fkbenjamin. There are some networking-wide issues with maintaining a healthy count of sync-committee peers at present. There are nascent talks about modifying the spec to increase the number of nodes which are required to connect to sync committees.

I'll leave this open so we can track the issue in Lighthouse specifically.

**Comment by mnguyen-io** [comment] 2021-12-22 16:18
We're also seeing similar issues.  We're using lighthouse as the VC

Restarting beacon node fixes it:

```
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.726 DEBG Sending pubsub messages                 topics: [Attestation(SubnetId(37))], count: 1, service: network
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.727 INFO Unaggregated attestation                validator: XXXXXX, src: api, slot: 2778383, epoch: 86824, delay_ms: 725, index: 4, head: 0xd1df7d0963ab48900eeedd7faf15e95d3b20f0577f8d64f6608a9b788bb9decb, service: val_mon
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.728 INFO Unaggregated attestation                validator: XXXXXX, src: api, slot: 2778383, epoch: 86824, delay_ms: 725, index: 4, head: 0xd1df7d0963ab48900eeedd7faf15e95d3b20f0577f8d64f6608a9b788bb9decb, service: val_mon
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.728 DEBG Processed HTTP API request              method: POST, path: /eth/v1/beacon/pool/attestations, status: 200 OK, elapsed: 3.356549ms
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.729 DEBG Sending pubsub messages                 topics: [SyncCommitteeMessage(SyncSubnetId(2))], count: 1, service: network
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 DEBG Sending pubsub messages                 topics: [Attestation(SubnetId(30))], count: 1, service: network
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 DEBG Sending pubsub messages                 topics: [SyncCommitteeMessage(SyncSubnetId(1))], count: 1, service: network
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 DEBG Sending pubsub messages                 topics: [SyncCommitteeMessage(SyncSubnetId(2))], count: 1, service: network
Dec 22 09:17:03 eth2-combo-bhs--mainnet--4 lighthouse[17274]: Dec 22 09:17:03.730 WARN Could not publish message               error: InsufficientPeers, service: libp2p
```

**Comment by 1swaraj** [comment] 2022-01-03 13:23
Our lighthouse consensus clients keeps disconnecting from peers and after a few minutes starts throwing these errors :-
WARN Could not publish message error: InsufficientPeers, service: libp2p
We are running multiple lighthouse nodes on the xdai network ( now gnosis ) and it happens with almost all of them
Restarting solves the issue for a few minutes but it usually presists

**Comment by michaelsproul** [comment] 2022-01-03 22:42
> We are running multiple lighthouse nodes on the xdai network ( now gnosis ) and it happens with almost all of them

Which commit are you running? One of the issues causing mass banning was late sync committee messages, which we've reduced the penalty for in `unstable`.

**Comment by mieubrisse** [comment] 2022-01-05 22:17
We're seeing the same problem trying to run Lighthouse in a localnet (2 Geth nodes, 1 Nimbus node, 1 Lighthouse node). The Beacon node spams the same "InsufficientPeers" output as above:
```
Jan 05 22:15:50.003 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:50.016 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:50.039 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:50.047 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:53.967 WARN Producing block that conflicts with head, slot: 113, message: this block is more likely to be orphaned, service: beacon
Jan 05 22:15:54.019 ERRO No valid eth1_data votes, `votes_to_consider` empty, outcome: casting `state.eth1_data` as eth1 vote, genesis_time: 1641419586, earliest_block_timestamp: 1641419586, lowest_block_number: 0, service: eth1_rpc
Jan 05 22:15:54.062 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:54.085 INFO Valid block from HTTP API               slot: 114, proposer_index: 83, root: 0x2558…4667, block_delay: 59.949ms
Jan 05 22:15:54.148 ERRO No valid eth1_data votes, `votes_to_consider` empty, outcome: casting `state.eth1_data` as eth1 vote, genesis_time: 1641419586, earliest_block_timestamp: 1641419586, lowest_block_number: 0, service: eth1_rpc
Jan 05 22:15:58.025 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:58.032 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:58.046 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:58.052 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:58.055 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:58.056 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:58.062 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:58.073 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:58.078 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:15:58.085 WARN Could not publish message               error: InsufficientPeers, service: libp2p
```

Of note: the Lighthouse Beacon node is in fact peered with the Nimbus Beacon node:
```
Jan 05 22:22:34.118 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:22:34.121 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:22:34.122 WARN Low peer count                          peer_count: 1, service: slot_notifier
Jan 05 22:22:34.122 INFO Synced                                  slot: 147, block:    …  empty, epoch: 4, finalized_epoch: 1, finalized_root: 0xe595…4e9b, exec_hash: 0xd496…2200 (verified), peers: 1, service: slot_notifier
Jan 05 22:22:34.125 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:22:34.128 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Jan 05 22:22:34.131 WARN Could not publish message               error: InsufficientPeers, service: libp2p
```

**Comment by pawanjay176** [comment] 2022-01-06 06:41
@mieubrisse Assuming it's a `SyncCommittee` message that couldn't get published, is your nimbus node subscribed to the required sync committee subnets? debug logs would be helpful if you have them.

**Comment by AgeManning** [comment] 2022-01-17 08:33
A full set of debug logs would be nice (especially if this is a recurring issue). 10-30 mins prior to the warning would be great.

**Comment by mnguyen-io** [comment] 2022-01-17 18:15
> A full set of debug logs would be nice (especially if this is a recurring issue). 10-30 mins prior to the warning would be great.

Problem hasn't come up in the past month or so for us so I'm unable to provide logs. I'll keep an eye out if it happens again as it use to happen some what frequently (every week or so).

Thanks

**Comment by AgeManning** [comment] 2022-01-17 23:52
My initial thinking is the following:
- Discovery takes a while (especially for subnets) to search for peers on a given subnet. If the network isn't rich with validating nodes subscribed to a log of subnets these can backlog and you can miss finding peers for subnets with a lower slot times. You can check this in the metrics, and look at the discovery queries queue. 
- Gossipsub has a backoff period of 1 minute. If you subscribe to a subnet with some peers, you have to wait 1 minute before re-subscribing. With a short slot time, you may subscribe and unsubscribe from a subnet and then lock yourself out from re-subscribing with the same peers for a whole minute. There is a PR that was just merged in gossipsub that lowers this to 10 seconds. It should come in the next lighthouse release, which may help

**Comment by mnguyen-io** [comment] 2022-01-20 19:07
> A full set of debug logs would be nice (especially if this is a recurring issue). 10-30 mins prior to the warning would be great.

Hi - this happened a few times today. Here are some logs that will hopefully help:

https://filebin.net/7f0e8m8yxzrlqa79/p2p.ZIP

The InsufficientPeers messages start to come in around Jan 20 15:23:51

Thanks

**Comment by 3cl1ps** [comment] 2022-09-01 06:19
had this bug on 3.0.0 once a week, updated to 3.0.1. following.

**Comment by 3cl1ps** [comment] 2022-09-05 07:00
error is still there, here just after a restart of the beacon service : 
```Sep 05 07:58:53 eth3 lighthouse[14158]: Sep 05 06:58:53.004 INFO Ready for the merge                     current_difficulty: 58003823773103876707853, terminal_total_difficulty: 58750000000000000000000, service: slot_notifier 
Sep 05 07:58:59 eth3 lighthouse[14158]: Sep 05 06:58:59.842 INFO New RPC block received                  hash: 0x2f82~@a094, slot: 4628093 
Sep 05 07:59:03 eth3 lighthouse[14158]: Sep 05 06:59:03.039 WARN Could not publish message               error: InsufficientPeers, service: libp2p 
Sep 05 07:59:03 eth3 lighthouse[14158]: Sep 05 06:59:03.567 WARN Gossip message published on retry       topic: beacon_attestation, service: libp2p

**Comment by michaelsproul** [comment] 2022-09-05 07:03
@3cl1ps it's possible (and likely) to get the warning immediately after start-up when the node hasn't got enough peers yet

If you're seeing it when the node otherwise has a high peer count, then that's an issue. One common cause is not having ports forwarded properly, can you please run `curl http://localhost:5052/lighthouse/nat` and show us the output?

**Comment by 3cl1ps** [comment] 2022-09-05 07:17
thx for fast  response
➜  ~ curl http://localhost:5052/lighthouse/nat
{"data":true}

full logs : 
https://paste.ubuntu.com/p/fxzmDVPkvn/

**Comment by 3cl1ps** [comment] 2022-09-05 07:45
debug log : 
http://sprunge.us/72J4Uh

and attestation (in)effectiveness on beaconcha.in

![image](https://user-images.githubusercontent.com/2938587/188399281-caca9c40-8c43-43eb-bdea-8b09839a12bc.png)

**Comment by AgeManning** [comment] 2022-09-06 06:54
I had a look through your logs. It looks like your system clock could be out. You are kicking peers for sending attestations at the wrong time. 

You should make sure your system clock is synced to a network clock, using something like ntp.

**Comment by 3cl1ps** [comment] 2022-09-06 07:26
thanks for looking into this. i used somer esta's guide with ntp service configured :
System clock synchronized: yes                         
NTP service: active

i had a case with this service being active but not sync, i'll watch this next time i have bad effectiveness.

for anyone reading this, this is a kind of error to look for : 
```Sep 05 08:31:55 eth3 lighthouse[26048]: Sep 05 07:31:55.984 DEBG Invalid attestation from network        type: "aggregated", peer_id: 16Uiu2HAm4zThK1zDn8jhGoLiycPZfYNiJyi4p1xcBHEY7q7jAHC4, block: 0x259168fa37ca9548abf2812bba8d551c386a12ac380bc7d91a400ee0fa134f98, reason: FutureSlot { attestation_slot: Slot(4628258), latest_permissible_slot: Slot(4628257) }```

edit : can confirm it's a ntp issue : 
```systemd-timesyncd[713]: Failed to set up connection socket: Address family not supported by protocol```
caused by disabling ipv6.

**Comment by AgeManning** [comment] 2022-09-07 01:24
Awesome. I'll add something to our FAQ docs, as a time sync issue is a common occurrence. 

If it is now behaving as expected, feel free to close the issue :)

**Comment by 3cl1ps** [comment] 2022-09-07 06:49
I can't, i didn't open it.

**Comment by AgeManning** [comment] 2022-09-07 23:22
Fair. Assuming this is resolved.

**Closed as completed by AgeManning** 2022-09-07 23:22 UTC
Labels: bug
