### ISSUE TITLE
error: UnknownHeadBlock

### ISSUE THREAD

**Issue by ankit2771991** [sigp/lighthouse#5272] opened 2024-02-20 15:45 UTC
## Description

We are facing the below issue
ERRO Failure verifying attestation for gossip, attestation_slot: 1045065, committee_index: 45, request_index: 0, error: UnknownHeadBlock { beacon_block_root: }

## Version

Lighthouse v4.6.0-1be5253
BLS library: blst-modern
SHA256 hardware acceleration: false
Allocator: jemalloc
Profile: maxperf
Specs: mainnet (true), minimal (false), gnosis (true)

Any idea what can be wrong or how to debug this issue?

**Comment by michaelsproul** [comment] 2024-02-20 22:15
Duplicate of https://github.com/sigp/lighthouse/issues/4699 which is fixed in v5.0.0

**Closed as completed by michaelsproul** 2024-02-20 22:15 UTC
