### ISSUE TITLE
/eth/v1/beacon/blinded_blocks BAD_REQUEST: Unsupported endpoint version: v1

### ISSUE THREAD

**Issue by koraykoska** [sigp/lighthouse#4491] opened 2023-07-11 16:14 UTC
## Description

Teku sends requests to `/eth/v1/beacon/blinded_blocks` on lighthouse and the below error occurs.

It might be related to #4262 or #4473 but because it's slightly different than both of those open issues, I wanted to open this issue just in case it's a different bug.

I disabled ssz blocks now on teku but cannot confirm if this solves the issue. If not it would be good to know before I find out during another block proposal.

```
java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = http://<domain>:<port>/eth/v1/beacon/blinded_blocks, status = 400, message = BAD_REQUEST: Unsupported endpoint version: v1)
at tech.pegasys.teku.validator.remote.typedef.ResponseHandler.defaultBadRequestHandler(ResponseHandler.java:129) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.typedef.ResponseHandler.handleResponse(ResponseHandler.java:93) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.AbstractTypeDefRequest.executeCall(AbstractTypeDefRequest.java:149) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.AbstractTypeDefRequest.postOctetStream(AbstractTypeDefRequest.java:142) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.SendSignedBlockRequest.sendSignedBlockAsSsz(SendSignedBlockRequest.java:85) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.SendSignedBlockRequest.sendSignedBlockAsSszOrFallback(SendSignedBlockRequest.java:76) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.typedef.handlers.SendSignedBlockRequest.sendSignedBlock(SendSignedBlockRequest.java:68) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.typedef.OkHttpValidatorTypeDefClient.sendSignedBlock(OkHttpValidatorTypeDefClient.java:87) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$sendSignedBlock$13(RemoteValidatorApiHandler.java:282) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:82) ~[teku-infrastructure-async-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.sendRequest(RemoteValidatorApiHandler.java:483) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$sendRequest$34(RemoteValidatorApiHandler.java:478) ~[teku-validator-remote-23.6.1.jar:23.6.1]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-23.6.1.jar:23.6.1]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[teku-infrastructure-async-23.6.1.jar:23.6.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
```

## Version

Docker version v4.3.0 (on Ubuntu 22.04)

## Present Behaviour

Block proposal fails because endpoint responds with 400 Unsupported endpoint version: v1

## Expected Behaviour

Working endpoint /eth/v1/beacon/blinded_blocks

## Steps to resolve

Hopefully disabling teku ssz blocks helps. Cannot confirm yet.

**Comment by jmcph4** [comment] 2023-07-11 22:07
This is definitely related to #3404 (hence the endpoint version part of the error). Do you have any logging output?

**Comment by koraykoska** [comment] 2023-07-12 09:19
@jmcph4 Here are the logs of lighthouse:

```
Jul 09 04:39:35.352 INFO Requesting blinded header from connected builder, parent_hash:<hash>, pubkey:<pubkey>, slot:>
Jul 09 04:39:35.645 INFO Requested blinded execution payload     parent_hash: <hash>, local_response_ms: 5, local_fee_recipient:<fee_recipient>, relay_response_ms: 292, relay_fee_re>
Jul 09 04:39:35.645 INFO Received local and builder payloads     parent_hash:<hash>, local_block_hash:<block>, relay_block_hash:<relay_block>>
Jul 09 04:39:35.645 INFO Relay block is more profitable than local block, relay_value: 47393647445848576, local_block_value: 5481107580841254, service: exec
Jul 09 04:39:35.953 WARN Error processing HTTP API request       method: POST, path: /eth/v1/beacon/blinded_blocks, status: 400 Bad Request, elapsed: 294.921µs
```

**Comment by jimmygchen** [comment] 2023-07-24 13:25
Thanks for the logs!

It does indeed look like this is related to #4262 (root cause) and #3404 (rejection handling issue). Both issues are currently being worked on, but disabling teku ssz blocks should help for now.

**Comment by michaelsproul** [comment] 2023-08-17 04:24
Closing as a duplicate of #4473

**Closed as not planned by michaelsproul** 2023-08-17 04:24 UTC
Labels: duplicate
