### ISSUE TITLE
--logfile weird behavior

### ISSUE THREAD

**Issue by mightypenguin** [sigp/lighthouse#1963] opened 2020-11-24 15:22 UTC
## Description

The '--logfile" directive has weird behavior

## Version
0.3.5

## Present Behaviour
lighthouse --logfile /some/logdir/logfile.txt bn

1. --logfile has to be in the command before "bn" or it will not be recognized.
2. error and exit happens if logfile does not already exist 

Describe the present behaviour of the application, with regards to this
issue.

## Expected Behaviour
(lighthouse should create it if it doesn't exist and should not throw an error)

How _should_ the application behave?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by pawanjay176** [comment] 2020-11-24 20:14
@mightypenguin 
> error and exit happens if logfile does not already exist

Not able to reproduce this behaviour. Can you post the exact error you are getting for this?

**Comment by divagant-martian** [comment] 2020-11-29 21:06
Not able to reproduce either. `lighthouse --logfile some-file bn` works. Also, the `--logfile` is a `lighthouse` option, not an option of the beacon node, but it is understandable that this is confusing. Marking the issue as an Ux issue

**Comment by michaelsproul** [comment] 2022-05-18 07:13
Fixed in more recent versions of Lighthouse thanks to @macladson's logging overhaul

**Closed by michaelsproul** 2022-05-18 07:13 UTC
Labels: t UX Logs Error Mgmt
